### ISSUE TITLE
Dependencies of requirements break `brew uses --recursive` and `brew deps` 

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/legacy-homebrew#50068] opened 2016-03-13 10:26 UTC
brew uses --recursive broken:
```
iMac-TMP:local joe$ git reset --hard origin/master
HEAD is now at 4b30df2 superenv: fix make_jobs regular expression
iMac-TMP:local joe$ brew uses pkg-config|grep python
python
python3
iMac-TMP:local joe$ brew uses python|grep libxml2
libxml2
iMac-TMP:local joe$ brew uses --recursive pkg-config|grep libxml2
iMac-TMP:local joe$ perl -pi -e 's/:python/"python"/' `brew --prefix`/Library/Formula/libxml2.rb
iMac-TMP:local joe$ brew uses --recursive pkg-config|grep libxml2
libxml2
```
brew deps broken:
```
iMac-TMP:local joe$ git reset --hard origin/master
HEAD is now at 4b30df2 superenv: fix make_jobs regular expression
iMac-TMP:local joe$ brew deps libxml2
python
iMac-TMP:local joe$ brew deps python
berkeley-db4
gdbm
homebrew/dupes/tcl-tk
icu4c
makedepend
openssl
pkg-config
readline
sqlite
iMac-TMP:local joe$ perl -pi -e 's/:python/"python"/' `brew --prefix`/Library/Formula/libxml2.rb
iMac-TMP:local joe$ brew deps libxml2
berkeley-db4
gdbm
homebrew/dupes/tcl-tk
icu4c
makedepend
openssl
pkg-config
python
readline
sqlite
iMac-TMP:local joe$ brew deps python
berkeley-db4
gdbm
homebrew/dupes/tcl-tk
icu4c
makedepend
openssl
pkg-config
readline
sqlite
iMac-TMP:local joe$
```

**Comment by mikemcquaid** [comment] 2016-03-13 16:28
Pretty sure this used to work. Can you check out some old revisions and see if you can pin down when it broke?

**Comment by ilovezfs** [comment] 2016-03-14 08:06
@mikemcquaid This seems to have never worked.

**Comment by mikemcquaid** [comment] 2016-03-14 08:17
Ok, good to know. Could you try to explain a bit more what the bug is? It's not obvious from your output above what "broken" means.

**Comment by ilovezfs** [comment] 2016-03-14 08:57
If libxml2 depends on python, then brew uses python returns libxml2.
If python depends on pkg-config, then brew uses pkg-config returns libxml2.

If libxml2 depends on python, and python depends on pkg-config, then brew uses --recursive pkg-config should return libxml2, but it does not.

In particular, I was trying to understand why with brew outdated returning
```
afflib, afl-fuzz, autogen, git, node, orc, pkg-config, sqlite, thefuck, vim
```
the reverse dependencies
```
dar, dos2unix, gettext, libmagic, libvpx, libxml2, pv, rpm, texi2html, yasm
```
were not being picked up by brew uses --recursive.

In particular the analysis of `dar` goes as follows:
```
dar -> gettext -> libxml2 -> python -> pkg-config

pkg-config: knows dar? no
python: knows dar? no
libxml2: knows dar? recursively only
gettext: knows dar? directly and recursively

pkg-config: knows gettext? no
python: knows gettext? recursively only
libxml2: knows gettext? directly and recursively

pkg-config: knows libxml2? no
python: knows libxml2? directly and recursively

pkg-config: knows python? directly and recursively
```

**Comment by mikemcquaid** [comment] 2016-03-14 09:00
Gotcha. For what it's worth `--recursive`'s algorithm has always seemed pretty broken and incorrect for me.

**Comment by ilovezfs** [comment] 2016-03-14 09:02
@mikemcquaid Well, it's pretty telling that replace :python with "python" makes it work as expected. Basically requirements of dependencies and dependencies of dependencies fall through, but dependencies of requirements do not.

**Comment by ilovezfs** [comment] 2016-03-14 14:50
@mikemcquaid As for the algorithm's generally being broken, I think some of that is due to

https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/uses.rb#L29
and
https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/uses.rb#L38

which both lead to false positives since `include?` will match totally random substrings.

**Comment by UniqMartin** [comment] 2016-03-18 02:34
@ilovezfs I think the observed issue is not an actual issue but a misunderstanding of how Homebrew's requirements system works. Unfortunately, the default output of `brew deps` only contributes to this confusion. Let me try to explain …

The cited formula `libxml2` has a dependency on Python, but it doesn't particularly care where that Python installation is coming from. This could be the `python` formula from Homebrew, but it doesn't have to be; it could as well be the Python already provided by OS X. The way to model this in Homebrew is to depend on a [requirement](http://www.rubydoc.info/github/Homebrew/homebrew/master/Requirement) (`depends_on :python` is just a shortcut for `depends_on PythonRequirement`).

The way this works for most requirements is to check a few conditions (e.g., if there's a working `python` binary in PATH) and *only if those conditions are not met*, proceed to add the `default_formula` associated with a requirement (in this case the `python` formula) to the dependency chain. This is a decision made when installing a formula that depends on a requirement. How a particular requirement was satisfied isn't recorded anywhere, but obviously can have an influence on the built formula.

This design allows for a great deal of flexibility, but unfortunately it also means that inspecting the dependencies via `brew deps` and `brew uses` (by design) cannot look beyond a requirement. To reiterate, a requirement could have been satisfied by a pre-installed system program, by a user-installed program not managed by Homebrew, by the requirement's default formula or by any other formula that satisfies the check done in a requirement. By replacing `:python` with `"python"` you're replacing this flexible mechanism with a hard-coded dependency on a specific formula. This removes ambiguity and puts Homebrew in control of the full dependency tree, but at the expense of losing this flexibility.

Using `brew deps` doesn't expose whether a dependency is a requirement or a specific formula; `brew deps --tree` (as seen below) does distinguish between the two, but has its own share of issues.

```
$ brew deps --tree libxml2
libxml2 (required dependencies)
└── :python
```

Feel free to follow up with questions, if anything is still unclear. I removed the “bug” label because of what I've written above and in the hopes of not having missed a crucial detail from your report.

**Comment by ilovezfs** [comment] 2016-03-18 02:37
Yes Martin I understand all of that, but nonetheless consider this s bug. Thanks.

**Comment by UniqMartin** [comment] 2016-03-18 02:53
> Yes Martin I understand all of that, but nonetheless consider this a bug.

Can you elaborate on why you think this is a bug? I tried pretty hard to explain that given the flexibility of the current requirements system, it's basically impossible to look beyond a requirement dependency-wise. (And it doesn't make sense to look beyond that boundary, if the requirement is satisfied by something different than the default formula of a requirement.)

Is offering this degree of flexibility a bug? Should the requirements system be taught to keep track of what was used to satisfy a requirement and if that happens to be a formula managed by Homebrew, include it in the dependency tree? Something completely different?

**Comment by tdsmith** [comment] 2016-03-18 03:56
Should we have `--resolve-requirements` and `--no-resolve-requirements` behaviors? `--resolve-requirements` would (pessimistically) resolve all possible requirements to the Homebrew package which provides them and `--no-resolve-requirements` would (optimistically) assume that all possible requirements are already fulfilled by the system as it stands.

Or maybe you could have `--resolve-requirements :all` vs `--resolve-requirements :none` vs `--resolve-requirements python`?

(Incidentally libxml2's python bits probably build fine against any ol' Python!)

**Comment by tdsmith** [comment] 2016-03-18 04:10
Regardless, it does seem annoying that, when running `brew deps` against a package with a Requirement, it is true that both:

a) Requirements are resolved to the name of their default formula, which is included in the output without annotation, and
b) the dependencies of the default formulas are not considered or included in the output.

**Comment by ilovezfs** [comment] 2016-03-18 04:46
:+1: 
The same (a) and (b) are equally true of `uses`.

**Comment by mikemcquaid** [comment] 2016-03-19 07:35
I think `brew deps` and `brew uses` should both always distinguish between requirements and dependencies and also possibly hide requirements by default (to avoid confusion and to avoid e.g. `brew install $(brew uses foo)` causing problems. I think resolving requirements is out of scope for both commands and isn't a bug.

**Comment by ilovezfs** [comment] 2016-03-19 08:20
@mikemcquaid That makes sense to me. If it were true that
```
(A ∈ {brew uses B} && B ∈ {brew uses C}) implies A ∈ {brew uses --recursive C}
```
and
```
(B ∈ {brew deps A} && C ∈ {brew deps B}) implies C ∈ {brew deps A}
```
I would consider there to be no bug.

**Comment by mikemcquaid** [comment] 2016-03-19 08:52
> @mikemcquaid That makes sense to me. If it were true that
> 
> MATHS

Sorry, it's been too long since I did MATHS. Can you elaborate and assume I'm an idiot? :sweat_smile:

**Comment by mikemcquaid** [comment] 2016-03-19 08:55
@ilovezfs Also, PRs welcome as usual. You've created a rod for your own back by submitting good PRs :wink:

**Comment by ilovezfs** [comment] 2016-03-19 09:22
If `brew uses B` has within its output `A` and `brew uses C` has within its output `B`, then `brew uses --recursive C` should have within its output `A`.

If `brew deps A` has within its output `B` and `brew deps B` has within its output `C`, then `brew deps A` should have within its output `C`.

Right now this is not true because in the `deps` and `uses` commands' output, `python` is used interchangeably to mean `python` in one breath and `:python` in the next breath. Given that `brew deps libxml2` returns `python` and that `brew deps python` returns `berkeley-db4, gdbm, homebrew/dupes/tcl-tk, icu4c, makedepend, openssl, pkg-config, readline, sqlite`, it should be the case that `brew deps libxml2` also contains that entire list in its output, but it doesn't. Now if `brew deps libxml2` instead returned nothing at all or returned `:python`, and `brew deps :python` returned nothing at all, then there would be no problem at all.

Another way to look at it is that the output "python" should mean the same thing as the input "python" but right now it doesn't.

**Comment by mikemcquaid** [comment] 2016-03-19 09:33
> If brew uses B has within its output A and brew uses C has within its output B, then brew uses --recursive C should have within its output A.

Agreed.


> If brew deps A has within its output B and brew deps B has within its output C, then brew deps A should have within its output C.

Agreed.

> Now if brew deps libxml2 instead returned nothing at all or returned :python, and brew deps :python returned nothing at all, then there would be no problem.

Agreed. I think I'd personally vote for it to return nothing unless you pass `--requirements` or something.

**Comment by ilovezfs** [comment] 2016-03-19 09:40
> I think I'd personally vote for it to return nothing unless you pass --requirements or something.

I wonder if `brew install :python` should be a silent no-op.

**Comment by UniqMartin** [comment] 2016-03-19 11:33
> MATHS

I agree it would be desirable to change both commands so that they

1. don't create confusing output and
2. meet the requirements of [transitivity](https://en.wikipedia.org/wiki/Transitive_relation) (that's the maths in one word; maybe the maths is awkward, but the concept should be pretty familiar to most programmers with some theoretical background).

> I think I'd personally vote for it to return nothing unless you pass `--requirements` or something.

Count my vote on this behavior, too. And if `--requirements` is passed, always output them with a prefixed `:` or some other means to disambiguate them from regular dependencies.

**Comment by ilovezfs** [comment] 2016-03-19 11:45
@UniqMartin Also, should have [closure](https://en.wikipedia.org/wiki/Closure_%28mathematics%29). :)

How would you handle :foo (or whatever other representation is used to disambiguate) when handed to brew install, etc.?

**Comment by UniqMartin** [comment] 2016-03-19 12:13
> How would you handle :foo (or whatever other representation is used to disambiguate) when handed to brew install, deps, etc.?

I think this should be an error. At least I can't think of any good and consistent semantics off the top of my head and just ignoring those arguments will probably lead to more confusion.

**Comment by ilovezfs** [comment] 2016-03-19 12:22
Errors would probably be fine assuming the requirements are not in the default output (as you said `--requirements` or whatever it ends up being called), but hopefully errors more sane than
```
bash-3.2$ brew install :python
Error: No available formula with the name ":python" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
bash-3.2$
```

**Comment by MikeMcQuaid** [comment] 2016-08-09 18:27
We're closing out all issues relating to features that no-one is implementing in the short term in favour of pull requests.

**Closed by MikeMcQuaid** 2016-08-09 18:27 UTC
Labels: features, usability
