### ISSUE TITLE
unixODBC bottle is broken

### ISSUE THREAD

**Issue by neanton** [Homebrew/legacy-homebrew#31090] opened 2014-07-24 15:00 UTC
In short:
Bottled unixodbc version contains a bug in a library that causes php to crash when connecting to odbc data source using PDO.

The problem is inside `./configure` script that detects proper shared library extension suffix.

Please see this bug report for detailed issue description: https://sourceforge.net/p/unixodbc/bugs/40/

**Comment by tdsmith** [comment] 2015-04-08 05:36
Emailed upstream to ask about applying Jack's fix.

**Comment by tdsmith** [comment] 2015-08-08 06:20
I think [this commit](http://sourceforge.net/p/unixodbc/code/118/) was intended to apply the fix [outlined here](https://sourceforge.net/p/unixodbc/bugs/40/#accd) but did not succeed.

**Comment by mikemcquaid** [comment] 2016-04-02 15:30
Is this still an issue?

**Comment by tdsmith** [comment] 2016-04-05 03:22
It looks like this is fixed in the 2.3.4 release.

**Closed** 2016-04-05 09:12 UTC
Labels: upstream issue
