### ISSUE TITLE
liboauth not building --universal

### ISSUE THREAD

**Issue by megrimm** [Homebrew/legacy-homebrew#50374] opened 2016-03-24 00:55 UTC
it only builds x86_64 and my app is complaining:

ld: warning: ignoring file /usr/local/lib/liboauth.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/liboauth.dylib

any chance to get it building universal?

thanks
mark

**Comment by dunn** [comment] 2016-03-24 01:54
If it can be built as a universal binary, we'd welcome a PR adding that as an option! Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

**Comment by megrimm** [comment] 2016-03-24 13:55
i could do this (make liboauth build universal) .... I am just not sure how :)

according to docs to compile for osx:

   On MacOS X 10.5 and later systems, you can create libraries and
executables that work on multiple system types--known as "fat" or
"universal" binaries--by specifying multiple `-arch' options to the
compiler but only a single `-arch' option to the preprocessor.  Like
this:

     ./configure CC="gcc -arch i386 -arch x86_64 -arch ppc -arch ppc64" \
                 CXX="g++ -arch i386 -arch x86_64 -arch ppc -arch ppc64" \
                 CPP="gcc -E" CXXCPP="g++ -E"


How to I add this to a formula? 

thanks!

**Comment by dunn** [comment] 2016-03-25 03:00
If it's just adding arch flags, then `option :universal` and then `ENV.universal_binary if build.universal?` in the install block should work.  Take a look at [`yaz.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/yaz.rb) for an example.

**Comment by megrimm** [comment] 2016-03-25 21:41
yes i did this but it did not work. this is what worked but im am not sure how to do this AND give is universal flag:

  
  option :universal

  def install
    ENV['CC']="gcc -arch i386 -arch x86_64"
    ENV['CXX']="g++ -arch i386 -arch x86_64"
    ENV['CPP']="gcc -E" 
    ENV['CXXCPP']="g++ -E"
    ENV.universal_binary if build.universal?
    system "./configure", "--disable-dependency-tracking",
                          "--prefix=#{prefix}",
                          "--disable-curl"

**Comment by dunn** [comment] 2016-03-25 21:58
Homebrew should set the environment itself; what happens if you remove all the `ENV` lines?

**Comment by megrimm** [comment] 2016-03-25 22:03
nothing... no universal build just x64.

yeah i had to add the ENV to get i386 + x64 otherwise no i386

On Fri, Mar 25, 2016 at 5:58 PM, Alex Dunn <notifications@github.com> wrote:

> Homebrew should set the environment itself; what happens if you remove all
> the ENV lines?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/issues/50374#issuecomment-201535563>
>



-- 
____________________
m.e.grimm, m.f.a, ed.m.
syracuse u., tc3
megrimm.net
____________________

**Comment by mistydemeo** [comment] 2016-03-25 22:41
I can't reproduce. I made this change:

```patch
diff --git a/Library/Formula/liboauth.rb b/Library/Formula/liboauth.rb
index d6d1e30..17c7efe 100644
--- a/Library/Formula/liboauth.rb
+++ b/Library/Formula/liboauth.rb
@@ -5,6 +5,8 @@ class Liboauth < Formula
   sha256 "0df60157b052f0e774ade8a8bac59d6e8d4b464058cc55f9208d72e41156811f"
   revision 1
 
+  option :universal
+
   bottle do
     cellar :any
     sha256 "3d5b00cf3fc8ed4032b1e5e618ab0bfbc962414373ac9bf45a5ee883a4277a07" => :yosemite
@@ -15,6 +17,7 @@ class Liboauth < Formula
   depends_on "openssl"
 
   def install
+    ENV.universal_binary if build.universal?
     system "./configure", "--disable-dependency-tracking",
                           "--prefix=#{prefix}",
                           "--disable-curl"
```

Which worked:

```
$ brew install liboauth --universal
==> Downloading https://downloads.sourceforge.net/project/liboauth/liboauth-1.0.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/liboauth-1.0.3.tar.gz
==> ./configure --prefix=/usr/local/Cellar/liboauth/1.0.3_1 --disable-curl
==> make install
🍺  /usr/local/Cellar/liboauth/1.0.3_1: 11 files, 194.3K, built in 11 seconds
$ lipo -info /usr/local/opt/liboauth/lib/liboauth.dylib
Architectures in the fat file: /usr/local/opt/liboauth/lib/liboauth.dylib are: x86_64 i386
```

**Comment by megrimm** [comment] 2016-03-26 00:59
yes that DID work. I am not sure what was happening on my end. thanks!


On Fri, Mar 25, 2016 at 6:42 PM, Misty De Meo <notifications@github.com>
wrote:

> I can't reproduce. I made this change:
>
> diff --git a/Library/Formula/liboauth.rb b/Library/Formula/liboauth.rb
> index d6d1e30..17c7efe 100644--- a/Library/Formula/liboauth.rb+++ b/Library/Formula/liboauth.rb@@ -5,6 +5,8 @@ class Liboauth < Formula
>    sha256 "0df60157b052f0e774ade8a8bac59d6e8d4b464058cc55f9208d72e41156811f"
>    revision 1
> +  option :universal+
>    bottle do
>      cellar :any
>      sha256 "3d5b00cf3fc8ed4032b1e5e618ab0bfbc962414373ac9bf45a5ee883a4277a07" => :yosemite@@ -15,6 +17,7 @@ class Liboauth < Formula
>    depends_on "openssl"
>
>    def install+    ENV.universal_binary if build.universal?
>      system "./configure", "--disable-dependency-tracking",
>                            "--prefix=#{prefix}",
>                            "--disable-curl"
>
> Which worked:
>
> $ brew install liboauth --universal
> ==> Downloading https://downloads.sourceforge.net/project/liboauth/liboauth-1.0.3.tar.gz
> Already downloaded: /Library/Caches/Homebrew/liboauth-1.0.3.tar.gz
> ==> ./configure --prefix=/usr/local/Cellar/liboauth/1.0.3_1 --disable-curl
> ==> make install🍺  /usr/local/Cellar/liboauth/1.0.3_1: 11 files, 194.3K, built in 11 seconds
> $ lipo -info /usr/local/opt/liboauth/lib/liboauth.dylib
> Architectures in the fat file: /usr/local/opt/liboauth/lib/liboauth.dylib are: x86_64 i386
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/issues/50374#issuecomment-201559761>
>



-- 
____________________
m.e.grimm, m.f.a, ed.m.
syracuse u., tc3
megrimm.net
____________________

**Comment by UniqMartin** [comment] 2016-04-07 13:38
Closing as the issue seems to be resolved. Please consider to contribute this change back as a PR in [`homebrew/core`](https://github.com/Homebrew/homebrew-core) if you'd like to see this change adopted in our official formula repository.

**Closed by UniqMartin** 2016-04-07 13:38 UTC
