### ISSUE TITLE
sysroot replacement breaks builds that use the current directory as sysroot

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/legacy-homebrew#50110] opened 2016-03-15 02:42 UTC
I was running `brew install llvm --with-clang --with-compiler-rt --HEAD`.
The output at the terminal:
```
[ 95%] Building CXX object projects/compiler-rt/lib/tsan/CMakeFiles/clang_rt.tsan_osx_dynamic.dir/rtl/tsan_clock.cc.o
cd /tmp/llvm20160314-23104-1owu8rc/projects/compiler-rt/lib/tsan && /usr/local/Library/ENV/4.3/clang++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Dclang_rt_tsan_osx_dynamic_EXPORTS -I/tmp/llvm20160314-23104-1owu8rc/projects/compiler-rt/lib/tsan -I/tmp/llvm20160314-23104-ymc5yj/projects/compiler-rt/lib/tsan -I/tmp/llvm20160314-23104-1owu8rc/include -I/tmp/llvm20160314-23104-ymc5yj/include -I/tmp/llvm20160314-23104-ymc5yj/projects/compiler-rt/lib/tsan/..  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -std=c++11 -Wall -std=c++11 -DNDEBUG -arch x86_64 -arch x86_64h -fPIC    -stdlib=libc++ -mmacosx-version-min=10.9 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -fno-function-sections -fno-lto -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -Wno-non-virtual-dtor -fPIE -fno-rtti -msse3 -Wframe-larger-than=512 -Wglobal-constructors --sysroot=. -o CMakeFiles/clang_rt.tsan_osx_dynamic.dir/rtl/tsan_clock.cc.o -c /tmp/llvm20160314-23104-ymc5yj/projects/compiler-rt/lib/tsan/rtl/tsan_clock.cc
clang: error: no such file or directory: 'CMakeFiles/clang_rt.tsan_osx_dynamic.dir/rtl/tsan_clock.cc.o'
make[3]: *** [projects/compiler-rt/lib/tsan/CMakeFiles/clang_rt.tsan_osx_dynamic.dir/rtl/tsan_clock.cc.o] Error 1
make[2]: *** [projects/compiler-rt/lib/tsan/CMakeFiles/clang_rt.tsan_osx_dynamic.dir/all] Error 2
make[1]: *** [projects/compiler-rt/CMakeFiles/compiler-rt.dir/rule] Error 2
make: *** [compiler-rt] Error 2
```
And the superenv info:
```
clang++ called with: -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Dclang_rt_tsan_osx_dynamic_EXPORTS -I/tmp/llvm20160314-23104-1owu8rc/projects/compiler-rt/lib/tsan -I/tmp/llvm20160314-23104-ymc5yj/projects/compiler-rt/lib/tsan -I/tmp/llvm20160314-23104-1owu8rc/include -I/tmp/llvm20160314-23104-ymc5yj/include -I/tmp/llvm20160314-23104-ymc5yj/projects/compiler-rt/lib/tsan/.. -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -std=c++11 -Wall -std=c++11 -DNDEBUG -arch x86_64 -arch x86_64h -fPIC -stdlib=libc++ -mmacosx-version-min=10.9 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -fno-function-sections -fno-lto -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -Wno-non-virtual-dtor -fPIE -fno-rtti -msse3 -Wframe-larger-than=512 -Wglobal-constructors --sysroot=. -o CMakeFiles/clang_rt.tsan_osx_dynamic.dir/rtl/tsan_clock.cc.o -c /tmp/llvm20160314-23104-ymc5yj/projects/compiler-rt/lib/tsan/rtl/tsan_clock.cc
superenv removed:  -Wall -W -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wall /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -O3 -Wframe-larger-than=512 -Wglobal-constructors --sysroot=.
superenv added:    -pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang++ -pipe -w -Os -march=native -stdlib=libc++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Dclang_rt_tsan_osx_dynamic_EXPORTS -I/tmp/llvm20160314-23104-1owu8rc/projects/compiler-rt/lib/tsan -I/tmp/llvm20160314-23104-ymc5yj/projects/compiler-rt/lib/tsan -I/tmp/llvm20160314-23104-1owu8rc/include -I/tmp/llvm20160314-23104-ymc5yj/include -I/tmp/llvm20160314-23104-ymc5yj/projects/compiler-rt/lib/tsan/.. -fPIC -fvisibility-inlines-hidden -Wno-unused-parameter -Wno-long-long -std=c++11 -std=c++11 -DNDEBUG -arch x86_64 -arch x86_64h -fPIC -stdlib=libc++ -mmacosx-version-min=10.9 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -fno-function-sections -fno-lto -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -Wno-non-virtual-dtor -fPIE -fno-rtti -msse3 -isysroot -o CMakeFiles/clang_rt.tsan_osx_dynamic.dir/rtl/tsan_clock.cc.o -c /tmp/llvm20160314-23104-ymc5yj/projects/compiler-rt/lib/tsan/rtl/tsan_clock.cc -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
```

I believe the precise spot is near the end of the command. The original has this:
```
--sysroot=. -o CMakeFiles/clang_rt.tsan_osx_dynamic.dir/rtl/tsan_clock.cc.o
```
which gets turned into this:
```
-isysroot -o CMakeFiles/clang_rt.tsan_osx_dynamic.dir/rtl/tsan_clock.cc.o
```
I'm guessing the compiler reads the file that should be output as the sysroot, and because the file to output doesn't exist yet, errors out.

A manual build with the same components completes just fine.

Also, it looks like the OS X SDK didn't make it into the final command, which might break more things?

**Comment by aw1621107** [comment] 2016-03-15 18:25
Could [this](https://patches.libav.org/patch/1337/) be part of the issue?
>Although not documented, clang does support the --sysroot flag, and it
>does the right thing.  Use this flag intead of -isysroot which only
>applies to header file searches, not the linker
Also [this](https://gcc.gnu.org/ml/gcc-patches/2010-09/msg00292.html) patch part:
> @item -isysroot @var{dir}
> @opindex isysroot
> This option is like the @option{--sysroot} option, but applies only to
>-header files.  See the @option{--sysroot} option for more information.
>+header files (except for Darwin targets, where it applies to both header
>+files and libraries).  See the @option{--sysroot} option for more
>+information.

**Comment by aw1621107** [comment] 2016-03-17 20:59
Looks like when refurbishing arguments `--sysroot=.` is processed as a single argument. Because `-o` comes afterword, `sdk` ends up being `-o` to produce `--sysroot -o`.

Still working on a workaround...

**Comment by aw1621107** [comment] 2016-03-20 23:05
It appears that leaving in `--sysroot`/`-isysroot` flags lets LLVM build. I'd imagine this would break other homebrew builds, though...

**Comment by ilovezfs** [comment] 2016-03-21 05:28
I cannot reproduce this:

https://gist.githubusercontent.com/ilovezfs/4b4c4136489bb8429311/raw/3f33d82f09e08d5e9c7b806f158b0647f493a0d6/gistfile1.txt

https://gist.github.com/anonymous/e08443e2524e53fb4892

**Comment by aw1621107** [comment] 2016-03-21 16:48
Hmmm, looks like I'll have to do some more digging. Thanks for the info!

**Comment by aw1621107** [comment] 2016-03-23 18:32
@ilovezfs Only instance of `--sysroot=.` I found in your logs was for src.cxx instead of for tsan. Strangely enough, the line is fairly similar:
```
-isysroot -o CMakeFiles/cmTC_a5783.dir/src.cxx.o -c /tmp/llvm20160320-9387-1f9mpud/CMakeFiles/CMakeTmp/src.cxx
```
I'll have to get a gist up at some point...

**Comment by UniqMartin** [comment] 2016-04-07 14:14
Seems like the issue is either resolved or no longer reproducible, thus closing for now. Feel free to report back once that changes and I'll gladly reopen. (Or maybe it's best to report that as a new issue then.)

**Closed by UniqMartin** 2016-04-07 14:14 UTC
