### ISSUE TITLE
can't upgrade percona-toolkit when percona-server installed

### ISSUE THREAD

**Issue by nijikon** [Homebrew/legacy-homebrew#35995] opened 2015-01-18 11:44 UTC
Hi guys,

I remember we did fix this once. But the issue came back. I can't upgrade percona-toolkit because dependency is unsatisfied. IMHO, this should work.

```
balrog:local n$ brew upgrade percona-toolkit
==> Upgrading 1 outdated package, with result:
percona-toolkit 2.2.12
==> Upgrading percona-toolkit
==> Installing percona-toolkit dependency: mysql
Error: Cannot install mysql because conflicting formulae are installed.

  percona-server: because mysql, mariadb, and percona install the same binaries.

Please `brew unlink percona-server` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```

**Comment by xu-cheng** [comment] 2015-01-18 15:06
It works for me. What's your `which mysql_config`?

**Comment by stephenreay** [comment] 2015-02-05 09:33
I have the same error as above, and in answer to your question:

    $ which mysql_config
    /usr/local/bin/mysql_config

    $ readlink /usr/local/bin/mysql_config
    ../Cellar/percona-server/5.6.22-71.0/bin/mysql_config

**Comment by dvankley** [comment] 2015-03-18 13:42
Ditto, same error here as well.

    $ which mysql_config
    /usr/local/bin/mysql_config
    
    $ readlink /usr/local/bin/mysql_config
    ../Cellar/percona-server/5.6.21-69.0/bin/mysql_config

**Comment by arvenil** [comment] 2015-03-18 23:49
@nijikon Hi Tomek ;p Did you solved that problem? :)

**Comment by nijikon** [comment] 2015-03-19 17:45
@arvenil Nope, I might find some time on sunday.

**Comment by arvenil** [comment] 2015-03-19 18:20
As a workaround `brew unlink percona-server; brew link mysql`

**Comment by tdsmith** [comment] 2016-04-05 03:50
cf #41595

**Comment by tdsmith** [comment] 2016-04-05 14:19
@nijikon Is this reproducible, do you think, or should we close it for now?

**Comment by MikeMcQuaid** [comment] 2016-08-10 09:05
We'll accept PRs for this but we're not actively working on it at this time.

**Closed by MikeMcQuaid** 2016-08-10 09:05 UTC
