### ISSUE TITLE
libcec's cec-client dylib not found (custom cellar path)

### ISSUE THREAD

**Issue by RSully** [Homebrew/legacy-homebrew#45359] opened 2015-10-26 21:49 UTC
Using a homebrew prefix other than `/usr/local` (probably the only reason this came to light):

```
> cec-client --info      
dlopen(libcec.3.dylib, 1): image not found
```

**Comment by DomT4** [comment] 2015-10-26 23:10
Unless upstream have hardcoded `/usr/local` themselves I'm not really sure how you're hitting this; I presume you didn't pour the bottle given it isn't tagged as `cellar :any` or similar?

**Comment by RSully** [comment] 2015-10-26 23:49
Compiled, no bottle. 

I tried the old formula for 2.2.0 and it works.

**Comment by DomT4** [comment] 2015-10-27 00:32
Huh. Here's an unusual thing:

```
# cec-client --info
dlopen(libcec.2.dylib, 1): image not found
```

As expected. But `cd $(brew --prefix libcec)/lib && cec-client --info` works fine. Does that reproduce for you, if you run the command from inside the `lib` directory?

**Comment by DomT4** [comment] 2015-10-27 00:47
Seems to be a general issue. Impacts `/usr/local` builds as well; the failure doesn't throw a bad exit code and so the `test do` mechanism interprets that as a successful test.

**Comment by RSully** [comment] 2015-10-27 00:48
Hm, when I install 2.2.0 and run `cec-client --info` it works (as reported before), but as soon as I open a new shell window it breaks as I get what you're reporting. Something iffy with my shell.

So yeah, seems to be general, effects both versions.

**Comment by DomT4** [comment] 2015-10-27 00:55
Would you mind reporting this upstream? If it reproduces regardless of prefix seems likely to be something they'll need to peek at.

**Comment by opdenkamp** [comment] 2015-11-25 17:16
c+p from what I've posted in the ticket you created (it's not an upstream issue):

cec-client does not have the path to the library compiled it. it's just loading the .so from your path like any other binary. if you use a non-standard path (one that's not in the default LD library path), then you must specify the search path (on Linux):
```sh
LD_LIBRARY_PATH="/directory/of/the/lib" cec-client -i
```

not sure if it's the same on OS X and dyloading, but it'll be similar.

**Comment by RSully** [comment] 2015-11-25 17:32
Perhaps part of the problem is that it is looking for `libcec.3.dylib`, but the only dylibs in `lib/` are `libcec.3.0.1.dylib`, `libcec.3.0.dylib`, `libcec.dylib`?

**Comment by opdenkamp** [comment] 2015-11-25 18:23
right, that would be something that could be changed on our end: https://github.com/Pulse-Eight/libcec/blob/release/include/cecloader.h#L121

but that wouldn't work in `/usr/local/` either. if it does put the symlinks when installed there and not in another dir, then that would be a bug in the cmake version that you're using really.

**Comment by opdenkamp** [comment] 2015-11-25 18:24
but it looks like we can drop the special can for OS X either way with cmake, which is nice ;-)

**Comment by RSully** [comment] 2016-03-20 17:33
This is not fixed in 3.1.0

**Comment by DomT4** [comment] 2016-03-20 18:14
Oh, I could no longer reproduce this on three different machines last night, so kind of presumed it had been. Exact same issue, or?

**Comment by RSully** [comment] 2016-03-20 21:51
```
> cec-client --info
dlopen(libcec.3.dylib, 1): image not found
```

**Comment by RSully** [comment] 2016-03-22 14:11
The above workaround does work though:

```
> cd $(brew --prefix libcec)/lib
> cec-client --info
libCEC version: 3.1.0, git revision: <unknown>, compiled on Sun Mar 20 06:30:56 UTC 2016 by brew@elcapitanvm.local on Darwin 15.3.0 (x86_64), features: P8_USB, DRM
```

Forcing `--build-from-source` does not fix, either.

**Comment by mikemcquaid** [comment] 2016-04-02 15:53
I'd be in favour of just setting the formula to note this doesn't work with a non-`/usr/local` prefix until upstream is able to fix this. It is an upstream issue because we're using a very standard build process.

**Comment by RSully** [comment] 2016-04-02 17:29
Closed accidentally? 

Is there a library path env var I could update to get this to work? Otherwise, I guess no choice other than waiting for upstream.

**Comment by MikeMcQuaid** [comment] 2016-08-09 12:05
Closing this out as it's an upstream issue that needs fixed there rather than here.

**Closed by MikeMcQuaid** 2016-08-09 12:05 UTC
Labels: upstream issue
