### ISSUE TITLE
man pages encoding problem

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/legacy-homebrew#49957] opened 2016-03-10 12:26 UTC
I see this 
![2016-03-10 14 26 02](https://cloud.githubusercontent.com/assets/922873/13669415/10fe0c72-e6cc-11e5-8bcb-37fb7a6461bd.png) instead of normal man pages.
Or in text:

```
ESC[1mNAMEESC[0m
       ESC[1mbrew ESC[22m- The missing package manager for OS X

ESC[1mSYNOPSISESC[0m
       ESC[1mbrew --versionESC[0m
       ESC[1mbrew ESC[4mESC[22mcommandESC[24m [ESC[1m--verboseESC[22m|ESC[1m-vESC[22m] [ESC[4moptionsESC[24m] [ESC[4mformulaESC[24m] ...
```

**Comment by yurikoles** [comment] 2016-03-10 12:36
Setting `export "PAGER=less -rins"` resolves this problem.

**Comment by apjanke** [comment] 2016-03-10 18:47
What terminal program are you viewing this in, and what command are you running to view the man page? Those look like text formatting terminal escape sequences (e.g. for bold and/or underlined text) which are being displayed literally instead of interpreted by the terminal.

**Comment by yurikoles** [comment] 2016-03-10 22:37
`man brew` in Terminal.app

**Comment by tdsmith** [comment] 2016-03-13 03:00
What are your locale variables set to? Other manpages render fine?

**Comment by yurikoles** [comment] 2016-03-14 15:28
I have "uk_UA.UTF-8", but same problem with "C".

**Comment by apjanke** [comment] 2016-03-14 18:31
That locale seems fine. (And "C" should work too, since those control characters are all ASCII/portable-character-set-compatible, If I'm reading that right.)

I'm a little stumped. Check your pager-related environment variables: `$PAGER`, `$MANPAGER`, `$LESS`, `$MORE`, and maybe others I don't know of; maybe you'll see something suspicious. (And maybe there's a relevant config file in your home directory?) If `export "PAGER=less -rins"` fixed it, might be something related there. That `-r` switch means to output terminal control characters as raw characters instead of quoted for human-readable display, and the raw output is what `man` needs. (The quoted control characters would look like your screenshot, too.) But I don't know what would have caused it to not do that by default in your case... that's the default behavior for `man` on every system that I can remember using, and I wasn't able to reproduce that broken behavior by fiddling with those variables or by using the `man -P` option to. (This was on OS X 10.9.5.)

Do other manpages render okay?

**Comment by yurikoles** [comment] 2016-03-15 03:06
I have checked on clean user profile, the issue persist.

**Comment by UniqMartin** [comment] 2016-04-08 20:26
> Other manpages render fine?

> Do other manpages render okay?

An answer to these question would help to debug this problem and would allow to determine if this is a Homebrew-specific issue or not. Frankly, I think it's the latter meaning we can't help you. Thus, closing until there's some strong indication that this is indeed related to Homebrew. Thanks for understanding!

**Closed by UniqMartin** 2016-04-08 20:26 UTC
Labels: user configuration
