### ISSUE TITLE
Squid error: FATAL: Ipc::Mem::Segment::create failed to shm_open(/squid-cf__queues.shm): (13) Permission denied

### ISSUE THREAD

**Issue by mconigliaro** [Homebrew/legacy-homebrew#41489] opened 2015-07-08 18:42 UTC
Squid doesn't run anymore. `squid -z` results in:

```
FATAL: Ipc::Mem::Segment::create failed to ftruncate(/squid-cf__metadata.shm): (22) Invalid argument
```

Trying to start squid before running `squid -z` results in the following error in `/usr/local/var/logs/cache.log`:

```
FATAL: Ipc::Mem::Segment::create failed to ftruncate(/squid-cf__metadata.shm): (22) Invalid argument

Squid Cache (Version 3.5.6): Terminated abnormally.
CPU Usage: 0.027 seconds = 0.020 user + 0.007 sys
Maximum Resident Size: 30523392 KB
Page faults with physical i/o: 0
```

Here's the output from `squid -v`

```
Squid Cache: Version 3.5.6
Service Name: squid
configure options:  '--disable-debug' '--disable-dependency-tracking' '--prefix=/usr/local/Cellar/squid/3.5.6' '--localstatedir=/usr/local/var' '--enable-ssl' '--enable-ssl-crtd' '--disable-eui' '--enable-pf-transparent' '--with-included-ltdl' '--with-openssl' 'CC=clang' 'LDFLAGS=-lresolv' 'CXX=clang++' 'PKG_CONFIG_PATH=/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10' --enable-ltdl-convenience
```

**Comment by mconigliaro** [comment] 2015-07-08 18:53
I reverted back to squid 3.4.12 via `brew edit squid` and copying and pasting [this version](https://github.com/Homebrew/homebrew/blob/5fbdb3d6814121acb21f5b2c5d8fe7009ac50b3c/Library/Formula/squid.rb). Now it works again:

```
$ squid -z
015/07/08 12:50:44 kid1| Making directories in /usr/local/var/cache/squid/01
2015/07/08 12:50:44 kid1| Making directories in /usr/local/var/cache/squid/02
2015/07/08 12:50:44 kid1| Making directories in /usr/local/var/cache/squid/03
2015/07/08 12:50:44 kid1| Making directories in /usr/local/var/cache/squid/04
2015/07/08 12:50:44 kid1| Making directories in /usr/local/var/cache/squid/05
2015/07/08 12:50:44 kid1| Making directories in /usr/local/var/cache/squid/06
2015/07/08 12:50:44 kid1| Making directories in /usr/local/var/cache/squid/07
2015/07/08 12:50:44 kid1| Making directories in /usr/local/var/cache/squid/08
2015/07/08 12:50:45 kid1| Making directories in /usr/local/var/cache/squid/09
2015/07/08 12:50:45 kid1| Making directories in /usr/local/var/cache/squid/0A
2015/07/08 12:50:45 kid1| Making directories in /usr/local/var/cache/squid/0B
2015/07/08 12:50:45 kid1| Making directories in /usr/local/var/cache/squid/0C
2015/07/08 12:50:45 kid1| Making directories in /usr/local/var/cache/squid/0D
2015/07/08 12:50:45 kid1| Making directories in /usr/local/var/cache/squid/0E
2015/07/08 12:50:45 kid1| Making directories in /usr/local/var/cache/squid/0F
```

**Comment by bfontaine** [comment] 2015-07-08 19:15
You might want to report this upstream.

**Comment by edsko** [comment] 2015-07-09 13:50
Got the same issue, but seems to be transient; eventually started up okay.

**Comment by dunn** [comment] 2015-08-08 16:07
Squid has just been updated; is this still an issue?

**Comment by mconigliaro** [comment] 2015-08-10 21:35
I can still reproduce this problem by `rm -rf`'ing the contents of my `cache_dir` and running `squid -z`, but @edsko is right; if you run `squid -z` enough times, it'll eventually work. Luckily this command isn't one you typically need to run often.

**Comment by dunn** [comment] 2015-08-10 21:39
Can you reproduce it with a version of squid installed outside Homebrew?

**Comment by cameron-simpson** [comment] 2015-09-24 23:12
I get this with squid from MacPorts. I believe I'm running squid 3.5.8. I can confirm that mconigliaro's suggestion of blowing away the cache and rebuilding it worked for me. It is always good after a reboot (regardless of age of cache) but after a few days of vigorous use (using most of the memory on my Mac regularly) I get to tbe unable to restart squid with the above symptom.

**Comment by dunn** [comment] 2015-09-26 00:50
Sounds like an upstream issue then, thanks! Could you let the developers know?

**Comment by wickedsp1d3r** [comment] 2015-09-26 16:06
Similar issues with squid 3.5.9,  `cache.log` has a message like this:

```
Squid Cache (Version 3.5.9): Terminated abnormally.
CPU Usage: 0.028 seconds = 0.022 user + 0.006 sys
Maximum Resident Size: 31293440 KB
Page faults with physical i/o: 0
FATAL: Ipc::Mem::Segment::create failed to ftruncate(/squid-cf__readers.shm): (22) Invalid argument
```

I run squid as launchd agent. It fails to launch a couple of times and then it starts up normally.

**Comment by timothyclarke** [comment] 2015-10-08 13:38
The recapie needs a mkdir -p /opt/local/var/squid/cache/squid as that's where as that's where it's trying to create this file

**Comment by andremueller** [comment] 2015-10-31 14:24
I had the same problem. My solution was: fix the permissions of the "/tmp" directory to **1777**. After that squid was running perfectly! Similarly dansguardian did start after this action, too. If that did not fix your problem it may be the file permissions of squid in /var/squid! Watch out which user/group squid is running as and adapt user/group of the /var/squid directory.

**Comment by wizsilex** [comment] 2015-11-17 09:28
Stop brew services squid with
	
	brew services stop squid
then start squid manually and make it recreate swap and cache files with:
    
    squid
    squid -z
then you can start squid again with brew services
    brew services start squid

this worked for me

**Comment by kenorb** [comment] 2015-11-30 19:48
@wizsilex Worked great, thank you.

I think these steps needs to be added in package intro text.

**Comment by bfontaine** [comment] 2015-12-16 14:30
Is it still an issue with the current version of Squid (3.5.11)?

**Comment by kemadz** [comment] 2015-12-24 07:35
Same issue with Squid 3.5.12

**Comment by erikthered** [comment] 2015-12-28 14:57
I am also seeing this with 3.5.12

**Comment by hi-q** [comment] 2015-12-28 18:58
Same issue

**Comment by nrGitHub** [comment] 2015-12-31 13:00
Same here

**Comment by mikemcquaid** [comment] 2015-12-31 13:14
Everyone will get this. I suggest working with upstream on a solution.

**Comment by ooglek** [comment] 2016-03-29 23:39
Any progress on upstream? Related ticket/issue/url?

**Comment by mikemcquaid** [comment] 2016-04-02 15:45
@ooglek File an issue upstream and then we'll have one.

**Comment by mikemcquaid** [comment] 2016-04-02 15:46
Given how long this issue has been around without resolution it's perhaps worth us just removing `squid` from Homebrew.

**Comment by erikthered** [comment] 2016-04-02 17:53
Is this still happening? I'm pretty sure I haven't seen this error happen
in the current version

**Comment by qianguozheng** [comment] 2016-04-11 09:15
@erikthered  I still got problem happen on 3.5.12

**Comment by Aashima89** [comment] 2016-04-11 14:57
I still face the same issue with 3.5.16 . It happens only in Centos 6

**service squid start **returns [FAILED]

Error in cache.log

Squid Cache (Version 3.5.16): Terminated abnormally.
CPU Usage: 0.017 seconds = 0.009 user + 0.008 sys
Maximum Resident Size: 38704 KB
Page faults with physical i/o: 0
2016/04/11 10:38:09| storeDirWriteCleanLogs: Starting...
2016/04/11 10:38:09|   Finished.  Wrote 0 entries.
2016/04/11 10:38:09|   Took 0.00 seconds (  0.00 entries/sec).
FATAL: Ipc::Mem::Segment::create failed to shm_open(/squid-cf__metadata.shm): (13) Permission denied

**Comment by mikemcquaid** [comment] 2016-04-11 15:35
@Aashima89 This is Homebrew, we don't support Linux.

**Comment by MikeMcQuaid** [comment] 2016-08-09 12:05
Closing this out as it's an upstream issue that needs fixed there rather than here.

**Closed by MikeMcQuaid** 2016-08-09 12:05 UTC
Labels: upstream issue
