### ISSUE TITLE
brew doctor false positive for outdated Xcode version due to Xcode.app on external drive

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/legacy-homebrew#47579] opened 2016-01-01 08:36 UTC
The "brew doctor" command will give a false positive that Xcode is outdated when an external drive containing an outdated Xcode.app is attached, even when the active Xcode folder, as reported by xcode-select -p, points to an up-to-date  Xcode command line tools folder.

Demonstration:
```
bash-3.2$ brew doctor 2>&1 | grep date | grep -v Store
Warning: Your Xcode (7.1.1) is outdated
Please update to Xcode 7.2.
bash-3.2$ xcode-select -p
/Library/Developer/CommandLineTools
bash-3.2$ pkgutil --file-info `xcode-select -p`|grep pkg-version
pkg-version: 7.2.0.0.1.1447826929
bash-3.2$ mdfind Xcode.app|grep Applications|while read app ; do printf "%s\t%s\n" "$(defaults read "$app"/Contents/Info.plist CFBundleShortVersionString)" "$app" ; done
7.1.1	/Volumes/asrunbootable/Applications/Xcode.app
7.1.1	/Volumes/CCC Target HD/Applications/Xcode.app
7.1.1	/Volumes/Yosemite HD/Applications/Xcode.app
```

**Comment by UniqMartin** [comment] 2016-01-01 17:18
I believe this behavior is correct, as we distinguish between Xcode (as in `Xcode.app`) and the Command Line Tools (CLT). You can see that distinction in the output of `brew config`. There is a certain overlap between the two, as they both provide compilers and a few other developer tools, but the CLT are no full replacement for Xcode and some formulae cannot be built without the latter. That's the reason we check for Xcode, even if you've selected the CLT as your primary developer tools.

Does this make sense and does this change your opinion on the output of `brew doctor`?

**Comment by ilovezfs** [comment] 2016-01-01 17:40
I can see that brew config draws a distinction between the two but it seems questionable whether there's anything to warn about if xcode-select is pointing at a current version, unless brew always opts for Xcode.app over the CLT despite your xcode-select setting? It certainly would be less "mysterious" if it reported out the CLT and Xcode.app versions when complaining.

It's also suspect to be using Xcode.app for such formula, if it's not the "active Xcode folder." Perhaps in such cases where the CLT is the active Xcode folder, an error should be thrown and xcode-select suggested as the means to fix it (or downloading Xcode.app suggested if Xcode.app is not installed).

I think the secondary bug here is that brew is "using" whatever Xcode.app it happens to find, as opposed to only the one found in /Applications. I can't see how it makes sense to pick up random Xcode.app's from external drives unless one was specifically set by the user using xcode-select.

```
bash-3.2$ brew config | grep Xcode
Xcode: 7.1.1 => /Volumes/asrunbootable/Applications/Xcode.app/Contents/Developer
bash-3.2$ ls -ld /Applications/Xcode.app
ls: /Applications/Xcode.app: No such file or directory
```

**Comment by UniqMartin** [comment] 2016-01-02 00:50
Thanks for the additional detail! I basically agree with your assessment: Homebrew could suggest using one of the `Xcode.app` it found, but shouldn't use it automatically, especially if it is located somewhere else than `/Applications`. And the choice made via `xcode-select` shouldn't be ignored either.

**Comment by apjanke** [comment] 2016-01-02 01:34
I agree about not warning in this case, and only complaining or auto-selecting an Xcode when trying to install a specific formula, and the `xcode-select` selection is a CLT. Warning about this case sounds bug-ish to me: this is a legit, supported configuration, and coincidentally having an Xcode.app on an external drive shouldn't interfere with things.

```
bash-3.2$ brew config | grep Xcode
Xcode: 7.1.1 => /Volumes/asrunbootable/Applications/Xcode.app/Contents/Developer
bash-3.2$ ls -ld /Applications/Xcode.app
ls: /Applications/Xcode.app: No such file or directory
```

I'm not sure this is an outright bug, but I'm not a fan of how `brew config` is reporting this. In this output, we can't differentiate between an `Xcode <version> => <location>` that is the result of a previously-set `xcode-select -s`, or from the search it's doing at the time of `brew config` to auto-find the Xcode. (If I understand the code right, an `xcode-select -s` pointing at an Xcode will always take priority.) Using the search result itself seems problematic to me as well, because it can change as a result of which external drives or internal partitions are mounted, or even as a result of your Spotlight indexing state, since [it's (I think?) using Spotlight to find it](https://github.com/Homebrew/homebrew/blob/2021e9a20b0237756c94e2889f791d39bbe7e2e6/Library/Homebrew/os/mac/xcode.rb#L55-L60).

At the least, I think it should be differentiated visually, and not produce a warning.

Personally, I'm uncomfortable with `brew` auto-finding Xcode.app if I don't have one set up, and it seems like it could affect repeatability and debuggability. (And performance, if it picks an Xcode on a USB disk or other slow mount.) Though I guess any Xcode.app of the right version should work, since there's no customization options for its installation. It's just a personal preference; I don't like this much auto-magic in my toolchains, but I can see either way being a legit choice on the user-friendliness spectrum. (Though maybe it should be limited to only Xcode.apps found on the system volume.)

This is the first time I've known this happens – I always thought that "Xcode" line was only based on `xcode-select` – and in retrospect I might have misdiagnosed things based on that earlier. It certainly complicates things, and maybe helps explain why I had a hard time learning how exactly `xcode-select` works.

 ilovezfs' suggestion, as I understand it – use the search for Xcode.app only as a suggestion to user, not automatically building formulae with it, raise an error at formula install time in the few cases where it actually causes problems, and not warning about this in `brew doctor` or including it in `brew config` – sounds like the best approach to me. (And maybe with "Xcode search result" being a separate line in `brew config` in the case where Xcode resolves to a CLT.)

Sorry for the long-windedness.

**Comment by mikemcquaid** [comment] 2016-01-03 17:37
> I agree about not warning in this case, and only complaining or auto-selecting an Xcode when trying to install a specific formula, and the xcode-select selection is a CLT.

The problem is: generally you want `xcode-select` pointing to the CLT rather than Xcode so this would be somewhat hard to detect warn for. I don't mind being more explicit to users if we can, though.

**Comment by UniqMartin** [comment] 2016-01-03 18:40
I have prepared a change that removes most of the magic and addresses the complaint of the issue author while still retaining some automatism to avoid unexpectedly breaking many Homebrew installations. I also had some preliminary discussion with Misty about this. I'll try to submit a PR shortly, but this requires a bit more local testing first.

**Comment by DomT4** [comment] 2016-01-04 03:16
> The problem is: generally you want xcode-select pointing to the CLT rather than Xcode

Why, out of curiosity?

**Comment by mikemcquaid** [comment] 2016-01-04 08:49
> Why, out of curiosity?

I can't remember exactly but because the headers can be slightly different and, for us, it ends up creating software which depends on the Xcode header locations (which aren't static between versions) rather than CLT locations (which are).

**Comment by MikeMcQuaid** [comment] 2016-05-28 16:29
Although I can see this is irritating I think this is either a WONTFIX or a @ilovezfs self-fix 😉

**Closed by MikeMcQuaid** 2016-05-28 16:29 UTC
Labels: bug

**Comment by ilovezfs** [comment] 2016-05-28 16:34
>or a @ilovezfs self-fix

LOL.

**Comment by MikeMcQuaid** [comment] 2016-05-28 16:47
@ilovezfs you can either read this as "fix this yourself" or "fix yourself" depending on how 😏 you think I am today 😉

**Comment by ilovezfs** [comment] 2016-05-28 16:48
@MikeMcQuaid Why do you think I was LOL'ing! :)
