### ISSUE TITLE
"brew tests" fails on 10.7

### ISSUE THREAD

**Issue by mvkorpel** [Homebrew/legacy-homebrew#48264] opened 2016-01-19 22:25 UTC
`brew tests` prints the following error message on Lion:

    Error: undefined method `find_all_by_name' for Gem::Specification:Class
    Please report this bug:
        https://git.io/brew-troubleshooting
    /usr/local/Library/Homebrew/utils.rb:241:in `install_gem_setup_path!'
    /usr/local/Library/Homebrew/cmd/tests.rb:20:in `tests'
    /usr/local/Library/Homebrew/extend/pathname.rb:317:in `cd'
    /usr/local/Library/Homebrew/extend/pathname.rb:317:in `chdir'
    /usr/local/Library/Homebrew/extend/pathname.rb:317:in `cd'
    /usr/local/Library/Homebrew/cmd/tests.rb:5:in `tests'
    /usr/local/Library/brew.rb:88:in `send'
    /usr/local/Library/brew.rb:88

Output of `brew config` and `brew doctor` is [here](https://gist.github.com/mvkorpel/41eea6f3fac72570600d).

**Comment by UniqMartin** [comment] 2016-01-19 22:48
Can you please add the output of `gem --version` to the information you already provided? Don't want to draw a conclusion yet, but since OS X 10.7 is no longer fully supported by either Apple or Homebrew (see the `brew doctor` output) we might decide to ignore this issue.

(I'm not trying to offend you, it's just that maintainer time is limited, basically none of us uses such an old OS X release, and we have no testing infrastructure for this OS X release.)

**Comment by mvkorpel** [comment] 2016-01-19 22:54
`gem --version` is `2.5.1`.

**Comment by UniqMartin** [comment] 2016-01-19 23:00
Sorry, I should have been more specific. Since Homebrew uses the system Ruby instead of the one you have installed via Homebrew, I need the output of `/usr/bin/gem --version`.

**Comment by mvkorpel** [comment] 2016-01-19 23:02
`/usr/bin/gem --version` is `1.3.6`.

**Comment by DomT4** [comment] 2016-02-13 03:10
Is this still an issue?

**Comment by mvkorpel** [comment] 2016-02-13 08:25
The problem is still there, but it doesn't bother me much. I just couldn't fully follow the instructions in [How To Open a Homebrew Pull Request (and get it merged)](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md) when I suggested a change to a Formula some time ago.

**Comment by ilovezfs** [comment] 2016-02-13 10:24
@mvitz @DomT4 @UniqMartin I actually hit the same issue on 10.8, and just verified that the "fix" works on 10.7 as well. You need to install homebrew ruby, and make sure to put these in your ~/.bash_profile:
```
export PATH=/usr/local/bin:$PATH
export HOMEBREW_RUBY_PATH=`which ruby`
export HOMEBREW_DEVELOPER=1
```
Here's a gist showing what to expect:
https://gist.github.com/ilovezfs/b755ed6f0698317146a4

**Comment by UniqMartin** [comment] 2016-02-13 14:52
FWIW, this issue is on my to do list, but because this only affects an unsupported OS X release (unsupported by Apple and Homebrew, cf. `brew doctor` output), it has pretty low priority. I'd prefer for it to stay open so I can keep track and eventually address it.

As @ilovezfs pointed out, one workaround is to switch to a non-system Ruby, e.g. the `ruby` formula, with a sufficiently new RubyGems:

```
export HOMEBREW_RUBY_PATH="$(brew --prefix)/opt/ruby/bin/ruby"
export HOMEBREW_DEVELOPER=1
```

`HOMEBREW_RUBY_PATH` will be ignored unless `HOMEBREW_DEVELOPER=1` is also set. Note that by using a non-system Ruby for Homebrew and by enabling developer mode via `HOMEBREW_DEVELOPER=1` you're on your own and should know what you are doing, including being able to debug any resulting issues yourself. We can't be expected to provide support for this configuration. (Just wanted to make that clear.)

> ```
> export PATH=/usr/local/bin:$PATH
> ```

This shouldn't be necessary for a normal OS X installation and every Homebrew user should have its `bin` directory in PATH anyway.

@ilovezfs What does `/usr/bin/gem --version` return on 10.8 and what is the exact version of your system, i.e. what does `sw_vers` output?

**Comment by ilovezfs** [comment] 2016-02-13 14:57
@UniqMartin That is necessary on OS X 10.n for n < 9, unless you want /usr/bin before /usr/local/bin. For OS X 10.n, n >= 9, Apple moved /usr/local/bin before /usr/local. Since I wrote `which ruby`, the order switch is required to pick up the brew ruby on both 10.7 and 10.8, and to give brew tools priority in general.

**Comment by ilovezfs** [comment] 2016-02-13 15:03
@UniqMartin 
```
Josephs-MacBook-Pro:~ joe$ /usr/bin/gem --version
1.3.6
Josephs-MacBook-Pro:~ joe$ /usr/bin/ruby --version
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
Josephs-MacBook-Pro:~ joe$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.8.5
BuildVersion:	12F2560
Josephs-MacBook-Pro:~ joe$ uname -a
Darwin Josephs-MacBook-Pro.local 12.6.0 Darwin Kernel Version 12.6.0: Wed Mar 18 16:23:48 PDT 2015; root:xnu-2050.48.19~1/RELEASE_X86_64 x86_64
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by UniqMartin** [comment] 2016-02-13 15:11
@ilovezfs Sorry, I didn't realize the order in the default PATH was changed in 10.9. Thanks for that piece of information! Just as an additional note: `HOMEBREW_RUBY_PATH` expects the full path and it doesn't require for that Ruby binary to be in PATH to work correctly. As for pre-installed RubyGems on OS X: Seems like it wasn't touched at all between 10.7.0 and 10.8.5.

**Comment by ilovezfs** [comment] 2016-02-13 15:17
@UniqMartin No problem. And of course `"$(brew --prefix)/opt/ruby/bin/ruby"` is a more robust way of specifying it.

**Comment by ilovezfs** [comment] 2016-02-20 11:03
@UniqMartin OK, git bisect found the revision that introduced the regression, and reverting that revision makes the problem go away.

The problem revision is 8f25e002fefce53af2225060bb5de2e59549e49d, which isn't surprising since it's the only place Gem::Specification.find_all_by_name is used.

Log showing the git revert is a successful workaround:
https://gist.github.com/ilovezfs/99bf57567f0de96f5627

**Comment by UniqMartin** [comment] 2016-02-20 12:50
@ilovezfs See https://github.com/Homebrew/homebrew/pull/46185#issuecomment-186585407 – I guess there's no need to repeat that here.

**Comment by MikeMcQuaid** [comment] 2016-08-09 18:24
We don't support this version of OS X so closing this out.

**Closed by MikeMcQuaid** 2016-08-09 18:24 UTC
Labels: 10.7, 10.8, bug
