### ISSUE TITLE
Issue running gnuplot

### ISSUE THREAD

**Issue by mstef005** [Homebrew/legacy-homebrew#50471] opened 2016-03-27 20:53 UTC
I've successfully used brew install gnuplot on OSX El Capitan.

Then calling gnuplot I get this error:

dyld: Library not loaded: /usr/local/lib/libjpeg.8.dylib
  Referenced from: /usr/local/opt/libtiff/lib/libtiff.5.dylib
  Reason: image not found
Trace/BPT trap: 5

I've uninstalled and re-installed gnuplot after updating brew and other suggestions I've found for similar issues. what else can I try to get gnuplot to run?

**Comment by ilovezfs** [comment] 2016-03-28 00:39
That means that you built something from source that now needs to be reinstalled.

```
brew uninstall libpng freetype fontconfig jpeg libtiff gd lua readline gnuplot
brew install gnuplot
```

**Comment by dunn** [comment] 2016-03-28 15:59
Looks like the problem is libtiff, `brew reinstall libtiff` should be enough.

**Comment by UniqMartin** [comment] 2016-04-07 13:33
Closing as the suggested `brew reinstall libtiff` should have resolved the issue. Feel free to report back if that's not the case.

**Closed by UniqMartin** 2016-04-07 13:33 UTC
