### ISSUE TITLE
csync fails w/ free of unallocated memory error

### ISSUE THREAD

**Issue by dastbe** [Homebrew/legacy-homebrew#36657] opened 2015-02-08 18:04 UTC
csync file1.txt file2.txt
malloc: *** error for object 0x7f855a404f24: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
zsh: abort      csync file1.txt file2.txt

with this installation of csync:

brew info csync                                                                                                                                                                                master
csync: stable 0.50.0 (bottled), HEAD
http://www.csync.org/
/usr/local/Cellar/csync/HEAD (43 files, 360K) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/csync.rb
==> Dependencies
Build: xz ✔, check ✔, cmake ✔, doxygen ✘
Required: argp-standalone ✔, iniparser ✔, sqlite ✔
Optional: doxygen ✘, libssh ✘, log4c ✘, samba ✘

brew update/upgrade'd and brew doctor says I am clean. Tried again on a separate computer and encountered the same issue.

**Comment by dastbe** [comment] 2015-02-08 18:05
Tried to get additional output from csync via debug levels and test functions, but they all failed with the same error (different address, obvi)

**Comment by asparagui** [comment] 2015-02-08 18:17
Can confirm.

**Comment by mikemcquaid** [comment] 2015-02-09 12:07
Is this also an issue when compiled outside Homebrew?

**Comment by dastbe** [comment] 2015-02-10 20:54
Just did a build outside of homebrew at csync HEAD and it failed w/ the same error.

It looks like @jacknagel worked on this formula 20 days ago. Was he able to build successfully and run it?

**Comment by jacknagel** [comment] 2015-02-10 20:58
If it fails outside of Homebrew, it needs to be reported upstream.

**Comment by luzpaz** [comment] 2015-06-12 12:46
Reported upstream: https://open.cryptomilk.org/issues/40

**Comment by m812215** [comment] 2015-11-11 07:12
...and AFAIK they have fixed it. I sent [Valgrind -dump](https://gist.github.com/m812215/d355425941f6a3e3db11) about crash and dev-team said it is now fixed, but they don't have any macs so test is impossible. Now git (git://git.csync.org/projects/csync.git) is not responding, so I can not clone and even try to build AND I think building csync is too difficult for me. At least earlier I could not...

**Comment by michalhasko** [comment] 2015-11-17 20:15
Hi all, I'm new to brew, only installed it today to get csync on my mac.
As @m812215 writes, I cannot confirm the issue is fixed. I've issued this command to build it from git:
```
brew install --build-from-source --HEAD csync
```
But I still get an error :-(
```
sync(24375,0x7fff7e1b5300) malloc: *** error for object 0x7fd8c9c04c83: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

**Comment by mikemcquaid** [comment] 2015-11-22 16:16
@michalhasko That's because the upstream software is broken and this needs reported to the upstream developers.

**Comment by m812215** [comment] 2015-11-22 16:31
@mikemcquaid It has been reported upstream and as I said - they said it is fixed, but they can not test it. Can anybody try to build it from the latest?

**Comment by mikemcquaid** [comment] 2015-11-22 16:33
It sounds like @michalhasko did and it's not broken. It also sounds to me like we should consider removing this software from Homebrew if the developers cannot test it on OS X.

**Comment by julou** [comment] 2016-04-01 14:15
Hi,

I just tried `brew install --build-from-source --HEAD csync` and got the same mallc error :(
Too bad, csync would be really useful for me!

Any help forward would be welcome…

**Comment by mikemcquaid** [comment] 2016-04-02 15:42
We should remove `csync` from Homebrew. Homebrew cannot help you here, only the `csync` developers (who do not test OS X).

**Closed** 2016-04-04 08:50 UTC
Labels: upstream issue
