### ISSUE TITLE
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/legacy-homebrew#33705] opened 2014-10-29 08:39 UTC
Vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH.

This demonstrates the issue:
https://gist.github.com/ilovezfs/3ed71c2b4f53ada23740

**Comment by lime-green** [comment] 2015-01-26 18:58
This wasn't working for me and my python was in `/usr/include/python2.7`. 

What I did to fix this was (you can subsititute the python directory with wherever yours is): `cmake_args.append( '-DPYTHON_INCLUDE_DIR=/usr/include/python2.7' )` to the `GetCmakeArgs` function in the file `.vim/bundle/YouCompleteMe/third_party/ycmd/build.py`

**Comment by TanakaYutaro** [comment] 2015-02-12 10:02
same issue.

**Comment by pibby** [comment] 2015-02-19 02:35
I had the same issue as well. First I used brew to remove vim, ruby, and python. I upgraded RVM with `rvm get head`, then told it to use the System ruby with `rvm system`. I re-installed python with `brew install python`, and then re-installed vim with `brew install vim --env-std --override-system-vim` and it installed without issue. I then went back to RVM and told it to use my preferred version `rvm use X.X.`. Hope that helps.

**Comment by ilovezfs** [comment] 2015-02-19 02:43
The issue is not finding a workaround, but fixing the bug.

**Comment by pibby** [comment] 2015-02-19 02:52
@ilovezfs I understand that. But when vim is vital to your every day work, sometimes you can't wait for a bug to be fixed. Vim is working again for me, so if that helps someone, it's better than nothing.

**Comment by ilovezfs** [comment] 2015-02-19 04:51
@pibby In that case, the title of the issue already contains the simplest workaround, which is to move /usr/bin/ruby so it's not first in the PATH while building.

**Comment by netroby** [comment] 2015-04-11 00:43
I have the same issue, how to resolv this problem?

**Comment by ilovezfs** [comment] 2015-04-11 00:54
The title of the issue has the solution if you read it carefully.

**Comment by netroby** [comment] 2015-04-11 00:59
I just fresh install homebrew, and the ruby was not installed by homebrew. 

I tried to remove ruby, but homebrew need ruby. 
So i have no idea.

**Comment by netroby** [comment] 2015-04-11 01:15
[netroby@localhost ~]$ brew install vim
==> Downloading http://ftp.debian.org/debian/pool/main/v/vim/vim_7.4.488.orig.tar.gz
Already downloaded: /home/netroby/.cache/Homebrew/vim-7.4.488.tar.gz
==> ./configure --prefix=/home/netroby/.linuxbrew --mandir=/home/netroby/.linuxbrew/Cellar/vim/7.4.488/share/man --enable-multibyte --with-tlib=ncurses --ena
==> make
make[1]: *** [objects/if_perl.o] Error 1
make[1]: *** 正在等待未完成的任务....
make[1]: Leaving directory '/tmp/vim20150411-1654-1gpsi4x/vim-7.4.488/src'
Makefile:26: recipe for target 'first' failed
make: *** [first] Error 2

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH (https://github.com/Homebrew/homebrew/issues/33705)
[netroby@localhost ~]$ whereis ruby
ruby: /usr/lib64/ruby /home/netroby/.linuxbrew/bin/ruby

**Comment by ilovezfs** [comment] 2015-04-11 01:29
First
```
brew install ruby
```
Then make sure /usr/local/bin/ruby (Homebrew's ruby you just installed) is before /usr/bin/ruby in your PATH.

```
echo 'export PATH=/usr/local/bin:$PATH' >> ~/.bash_profile
source ~/.bash_profile
```

And now install vim.

```
brew install vim
```

**Comment by netroby** [comment] 2015-04-11 02:18
Still not working 

```

[netroby@localhost ~]$ whereis ruby
ruby: /usr/local/linuxbrew/bin/ruby
[netroby@localhost ~]$ brew install vim
==> Downloading http://ftp.debian.org/debian/pool/main/v/vim/vim_7.4.488.orig.tar.gz
Already downloaded: /home/netroby/.cache/Homebrew/vim-7.4.488.tar.gz
==> ./configure --prefix=/usr/local/linuxbrew --mandir=/usr/local/linuxbrew/Cellar/vim/7.4.488/share/man --enable-multibyte --with-tlib=ncurses --enable-csco
==> make
make[1]: *** [objects/if_perl.o] Error 1
make[1]: *** 正在等待未完成的任务....
make[1]: Leaving directory '/tmp/vim20150411-9920-73nlgh/vim-7.4.488/src'
Makefile:26: recipe for target 'first' failed
make: *** [first] Error 2

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH (https://github.com/Homebrew/homebrew/issues/33705)

```

**Comment by martinsotirov** [comment] 2015-04-13 08:31
@ilovezfs, this didn't work. /usr/local/bin is before /usr/bin in my PATH but homebrew still fails to compile vim.

**Comment by ilovezfs** [comment] 2015-04-13 10:38
They are different issues. The error I get is

```
_error_print in if_ruby.o
```

The error you get is

```
make[1]: *** [objects/if_perl.o] Error 1
```

So perhaps an issue with your perl?

**Comment by jacknagel** [comment] 2015-04-15 00:46
I see some linuxbrew things here. If you're having issues with linuxbrew, please report it there. This issue tracker is for OS X homebrew only.

**Comment by zhangyonglei** [comment] 2015-05-04 03:31
Install vim-7.4.712 failed:

```
checking whether byte ordering is bigendian... no
checking for rlim_t... yes
checking for stack_t... yes
checking whether stack_t has an ss_base field... no
checking --with-tlib argument... ncurses
checking for linking with ncurses library... OK
checking for tgetent()... configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      Or specify the name of the library with --with-tlib.
==> Formula
Path: /usr/local/Library/Formula/vim.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 1ef1632603b0819746d19c972b67f5e2729f97bf
Last commit: 22 minutes ago
HOMEBREW_PREFIX: /usr/local
```

**Comment by jacknagel** [comment] 2015-06-26 01:55
I can't reproduce this ("build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH") with the latest vim (7.4.712).

**Comment by ilovezfs** [comment] 2015-06-26 13:16
I was just able to reproduce the issue in a clean Mountain Lion vm. I was not able to reproduce the issue in a clean Yosemite vm. I have not checked Mavericks.

**Comment by jacknagel** [comment] 2015-06-30 02:12
The root cause is the same as #38047, as discussed in #40255. vim's configure script is misdetecting the header directory for ruby 1.8:

```
checking Ruby header files... /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0
```

**Comment by xavierartot** [comment] 2015-07-01 03:08
Same for me

**Comment by BigL** [comment] 2015-07-31 14:39
Hi guys,

I had been battling with this error  <b>( see bold text )</b>

So to solve it I had this error (  to install Vim 7.4.x on mac ) before:
<code>
brew install vim --with-lua -d
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/vim.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/lua.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/ex-vi.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/vim.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/lua.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/python.rb
==> Downloading https://mirrors.kernel.org/debian/pool/main/v/vim/vim_7.4.712.orig.tar.gz
Already downloaded: /Library/Caches/Homebrew/vim-7.4.712.tar.gz
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.712_1/share/man --enable-multibyte --
  <b>Referenced from: /usr/local/bin/gawk</b>
  Reason: image not found
auto/config.status: line 1108: 75192 Done                    eval sed \"\$ac_sed_extra\" "$ac_file_inputs"
     75193 Trace/BPT trap: 5       | $AWK -f "$ac_tmp/subs.awk" > $ac_tmp/out
config.status: error: could not create auto/config.mk
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.712_1/share/man --enable-multibyte --with-tlib=ncurses --enable-cscope --with-features=huge --with-compiledby=Homebrew --enable-luainterp --enable-perlinterp --enable-pythoninterp --enable-rubyinterp --enable-gui=no --without-x
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1

READ THIS: https://git.io/brew-troubleshooting

bThese open issues may also help:
vim 7.4.769 https://github.com/Homebrew/homebrew/pull/41494
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH https://github.com/Homebrew/homebrew/issues/33705
</code>

To solve this bug I had to :
<code>
~$ brew install gawk
==> Downloading https://homebrew.bintray.com/bottles/gawk-4.1.3.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gawk-4.1.3.yosemite.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/gawk
Target /usr/local/bin/gawk
already exists. You may want to remove it:
  rm '/usr/local/bin/gawk'

To force the link and overwrite all conflicting files:
  brew link --overwrite gawk

To list all files that would be deleted:
  brew link --overwrite --dry-run gawk

Possible conflicting files are:
/usr/local/bin/gawk
/usr/local/bin/igawk
/usr/local/share/awk/assert.awk
/usr/local/share/awk/bits2str.awk
/usr/local/share/awk/cliff_rand.awk
/usr/local/share/awk/ctime.awk
/usr/local/share/awk/ftrans.awk
/usr/local/share/awk/getopt.awk
/usr/local/share/awk/gettime.awk
/usr/local/share/awk/group.awk
/usr/local/share/awk/join.awk
/usr/local/share/awk/libintl.awk
/usr/local/share/awk/noassign.awk
/usr/local/share/awk/ord.awk
/usr/local/share/awk/passwd.awk
/usr/local/share/awk/quicksort.awk
/usr/local/share/awk/readable.awk
/usr/local/share/awk/rewind.awk
/usr/local/share/awk/round.awk
/usr/local/share/awk/strtonum.awk
/usr/local/share/awk/walkarray.awk
/usr/local/share/awk/zerofile.awk
/usr/local/share/info/gawk.info
/usr/local/share/info/gawkinet.info
==> Summary
🍺  /usr/local/Cellar/gawk/4.1.3: 63 files, 2.9M

~$ brew link --overwrite gawk
Linking /usr/local/Cellar/gawk/4.1.3... 45 symlinks created

~$ brew install vim --with-lua -d
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/vim.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/lua.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/ex-vi.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/vim.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/lua.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/python.rb
==> Downloading https://mirrors.kernel.org/debian/pool/main/v/vim/vim_7.4.712.orig.tar.gz
Already downloaded: /Library/Caches/Homebrew/vim-7.4.712.tar.gz
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.712_1/share/man --enable-multibyte --
==> make
==> make install prefix=/usr/local/Cellar/vim/7.4.712_1 STRIP=true
Fixing /usr/local/Cellar/vim/7.4.712_1/bin/vim permissions from 755 to 555
Fixing /usr/local/Cellar/vim/7.4.712_1/bin/vimtutor permissions from 755 to 555
Fixing /usr/local/Cellar/vim/7.4.712_1/bin/xxd permissions from 755 to 555
/usr/local/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/vim.rb
🍺  /usr/local/Cellar/vim/7.4.712_1: 1606 files, 26M, built in 37 seconds
<code>

**Comment by mprimeaux** [comment] 2015-09-13 17:47
@pibby Thanks for the work-around. Looking forward to the fix, also.

**Comment by phette23** [comment] 2015-10-08 05:25
If anyone else comes here, I also encountered an error installing vim but text & solution were different. I was on El Capitan but without the updated Xcode (6.4 and not 7.0) and got this:

```sh
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.889/share/man --enable-multibyte --with-tlib=ncurses --enab
==> make
Last 15 lines from /Users/phette23/Library/Logs/Homebrew/vim/02.make:
^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:12: note: previous definition is here
@interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:32: error: method type specifier must start with '-' or '+'
@interface NSArray<ObjectType> (NSExtendedArray)
                               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:33: error: expected a type
@interface NSArray<ObjectType> (NSExtendedArray)
                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [objects/os_macosx.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2
```

Updating to XCode 7.0 worked, as I suspected from the messages about NS* stuff.

**Comment by tczf1128** [comment] 2015-10-11 14:57
Same issue. :)

**Comment by JASON0916** [comment] 2015-10-15 01:47
I tried all methods referred before but not solved. However when i tried to type in "brew install vim" once again, the problem is solved... and i don't know why

**Comment by Phrohdoh** [comment] 2015-10-17 17:16
```bash
$ brew info ruby
ruby: stable 2.2.3 (bottled), HEAD
Powerful, clean, object-oriented scripting language
https://www.ruby-lang.org/
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ruby.rb
==> Dependencies
Build: pkg-config ✔
Required: libyaml ✘, openssl ✔
Recommended: readline ✔
Optional: gdbm ✔, gmp ✔, libffi ✔
==> Options
--universal
        Build a universal binary
--with-doc
        Install documentation
--with-gdbm
        Build with gdbm support
--with-gmp
        Build with gmp support
--with-libffi
        Build with libffi support
--with-suffix
        Suffix commands with '22'
--with-tcltk
        Install with Tcl/Tk support
--without-readline
        Build without readline support
--HEAD
        Install HEAD version

$ rvm
-bash: rvm: command not found

$ rbenv
-bash: rbenv: command not found

$ brew install vim --override-system-vi
==> Downloading https://github.com/vim/vim/archive/v7.4.891.tar.gz
Already downloaded: /Library/Caches/Homebrew/vim-7.4.891.tar.gz
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.891/share/man --enable-multibyte --with-tlib=ncurses --enable-cscope --with-features=huge --with-compiledby=Homebrew --enable-perlint
==> make
Last 15 lines from /Users/thill/Library/Logs/Homebrew/vim/02.make:
/usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/undo.o undo.c
/usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/window.o window.c
/usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -g  -DPERL_DARWIN -fno-strict-aliasing -fstack-protector  -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE  -o objects/if_perl.o auto/if_perl.c
/usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -g  -DPERL_DARWIN -fno-strict-aliasing -fstack-protector  -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE  -o objects/if_perlsfio.o if_perlsfio.c
/usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -I/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DPYTHON_HOME='"/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7"' -fPIE  -o objects/if_python.o if_python.c
/usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0 -DRUBY_VERSION=20 -o objects/if_ruby.o if_ruby.c
In file included from if_ruby.c:109:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^
1 error generated.
make[1]: *** [objects/if_ruby.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH https://github.com/Homebrew/homebrew/issues/33705
Warning:
```

`brew gist-logs vim`: https://gist.github.com/anonymous/df3f8c821e37719726f8
`brew install -d vim`: https://gist.github.com/Phrohdoh/ecfc9796ae5e9ed974da

**Comment by cacampbell** [comment] 2015-10-28 22:26
Yep, Me too thanks

brew install vim --with-features=huge
==> Downloading https://github.com/vim/vim/archive/v7.4.898.tar.gz
Already downloaded: /Library/Caches/Homebrew/vim-7.4.898.tar.gz
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.898/share/man --enable-multibyte --with-tlib=ncur
==> make
Last 15 lines from /Users/chris/Library/Logs/Homebrew/vim/02.make:
      _string_convert_ext in mbyte.o
     (maybe you meant: _my_iconv_open)
  "_iconv_close", referenced from:
      _readfile in fileio.o
      _buf_write in fileio.o
      _utf_find_illegal in mbyte.o
      _my_iconv_open in mbyte.o
      _convert_setup_ext in mbyte.o
  "_iconv_open", referenced from:
      _my_iconv_open in mbyte.o
     (maybe you meant: _my_iconv_open)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [vim] Error 1
make: *** [first] Error 2

**Comment by cacampbell** [comment] 2015-10-28 22:30
and again... with gcc-5

brew install --cc=gcc-5 vim --with-features=huge
==> Downloading https://github.com/vim/vim/archive/v7.4.898.tar.gz
Already downloaded: /Library/Caches/Homebrew/vim-7.4.898.tar.gz
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.898/share/man --enable-multibyte --with-tlib=ncur
==> make
Last 15 lines from /Users/chris/Library/Logs/Homebrew/vim/02.make:
                                                                                                                                                         ^
/System/Library/Frameworks/CoreData.framework/Headers/NSMergePolicy.h:113:229: error: expected '>' before '*' token
 - (instancetype)initWithConstraint:(NSArray<NSString *> *)contraint databaseObject:(nullable NSManagedObject*)databaseObject databaseSnapshot:(nullable NSDictionary *)databaseSnapshot conflictingObjects:(NSArray<NSManagedObject *> *)conflictingObjects conflictingSnapshots:(NSArray  *)conflictingSnapshots NS_DESIGNATED_INITIALIZER;
                                                                                                                                                                                                                                     ^
/System/Library/Frameworks/CoreData.framework/Headers/NSMergePolicy.h:113:229: error: cannot find protocol declaration for 'NSManagedObject'
/System/Library/Frameworks/CoreData.framework/Headers/NSMergePolicy.h:148:76: error: expected '>' before '*' token
  - (BOOL)resolveOptimisticLockingVersionConflicts:(NSArray<NSMergeConflict *> *)list error:(NSError **)error NS_AVAILABLE(10_11, 9_0);
                                                                            ^
/System/Library/Frameworks/CoreData.framework/Headers/NSMergePolicy.h:148:76: error: cannot find protocol declaration for 'NSMergeConflict'
/System/Library/Frameworks/CoreData.framework/Headers/NSMergePolicy.h:153:66: error: expected '>' before '*' token
 - (BOOL)resolveConstraintConflicts:(NSArray<NSConstraintConflict *> *)list error:(NSError **)error NS_AVAILABLE(10_11, 9_0);
                                                                  ^
/System/Library/Frameworks/CoreData.framework/Headers/NSMergePolicy.h:153:66: error: cannot find protocol declaration for 'NSConstraintConflict'
make[1]: *** [objects/os_macosx.o] Error 1
make: *** [first] Error 2

**Comment by KiYugadgeter** [comment] 2015-11-03 00:09
Me too.

OS: El capitan
XCode: 7.1
<pre>
==> Reinstalling vim with --with-lua, --with-python3, --override-system-vi
==> Cloning https://github.com/vim/vim.git
Updating /Library/Caches/Homebrew/vim--git
==> Checking out branch master
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/HEAD/share/man --enable-multibyte --with-tlib=ncurses --enable-cscope --with-features=huge --with-compiledby=Homebrew --enable-luainterp --enable-python3interp --enable-perlinterp --enable-rubyinterp --enable-gui=no --without-x
==> make
==> make install prefix=/usr/local/Cellar/vim/HEAD STRIP=true
Last 15 lines from /Users/username/Library/Logs/Homebrew/vim/03.make:
installing /usr/local/Cellar/vim/HEAD/share/man/ru.UTF-8/man1/xxd.1
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/syntax; chmod 644 *.vim README.txt
cd ../runtime/indent; cp *.vim README.txt /usr/local/Cellar/vim/HEAD/share/vim/vim74/indent
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/indent; chmod 644 *.vim README.txt
cd ../runtime/autoload; cp *.vim README.txt /usr/local/Cellar/vim/HEAD/share/vim/vim74/autoload
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/autoload; chmod 644 *.vim README.txt
cd ../runtime/autoload/xml; cp *.vim /usr/local/Cellar/vim/HEAD/share/vim/vim74/autoload/xml
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/autoload/xml; chmod 644 *.vim
cd ../runtime/plugin; cp *.vim README.txt /usr/local/Cellar/vim/HEAD/share/vim/vim74/plugin
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/plugin; chmod 644 *.vim README.txt
cd ../runtime/ftplugin; cp *.vim README.txt logtalk.dict /usr/local/Cellar/vim/HEAD/share/vim/vim74/ftplugin
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/ftplugin; chmod 644 *.vim README.txt
cd ../runtime/compiler; cp *.vim README.txt /usr/local/Cellar/vim/HEAD/share/vim/vim74/compiler
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/compiler; chmod 644 *.vim README.txt
make: *** [install] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH https://github.com/Homebrew/homebrew/issues/33705
</pre>

**Comment by jasonzoladz** [comment] 2015-11-06 19:41
Same issue as @KiYugadgeter

**Comment by greyg00s** [comment] 2015-11-13 02:43
I had the same issue as well. I ran "brew doctor" and followed all suggestions until I got the message "Your system is ready to brew." Afterwards I issued "brew install vim && brew install macvim" and everything worked out. Hope this helps

**Comment by Alykoff** [comment] 2015-12-05 21:18
I get the same error as @Phrohdoh

**Comment by Alykoff** [comment] 2015-12-06 10:20
```bash
brew install ruby
```
It's help for me.

**Comment by Pierpo** [comment] 2016-01-23 00:26
The same error occurred on my system while I was trying to upgrade Vim. I tried a few methods which didn't work.

The one that did was simply to deinstall and reinstall Vim (instead of upgrading).
```
brew remove vim
brew install vim
```

**Comment by ilovezfs** [comment] 2016-01-23 09:20
@jacknagel Regarding the original issue, adding <code>-framework Ruby</code> to the <code>LDFLAGS</code> when `which ruby` is /usr/bin/ruby allows it to build. However, it does end up linked against both, though I'm not sure that's actually a problem.

```
diff --git a/Library/Formula/vim.rb b/Library/Formula/vim.rb
index 9de226b..477dc54 100644
--- a/Library/Formula/vim.rb
+++ b/Library/Formula/vim.rb
@@ -49,6 +49,10 @@ class Vim < Formula
       ENV.append "LDFLAGS", "-F#{buildpath}/Frameworks"
     end
 
+    if build.with?("ruby") && which("ruby").to_s == "/usr/bin/ruby"
+       ENV.append "LDFLAGS", "-framework Ruby"
+    end
+
     opts = []
 
     (LANGUAGES_OPTIONAL + LANGUAGES_DEFAULT).each do |language|
```

```
bash-4.3$ otool -L /usr/local/bin/vim|grep uby
	/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/libruby.1.dylib (compatibility version 1.8.0, current version 1.8.7)
	/usr/local/opt/ruby/lib/libruby.2.3.0.dylib (compatibility version 2.3.0, current version 2.3.0)
```

If brew's ruby comes, first in the path, then you get
```
bash-4.3$ otool -L /usr/local/bin/vim|grep uby
	/usr/local/opt/ruby/lib/libruby.2.3.0.dylib (compatibility version 2.3.0, current version 2.3.0)
```

**Comment by MikeMcQuaid** [comment] 2016-08-09 12:04
Closing this out as it's an upstream issue that needs fixed there rather than here.

**Closed by MikeMcQuaid** 2016-08-09 12:04 UTC
Labels: upstream issue
