### ISSUE TITLE
"exotic" $TERM and `brew install` errors

### ISSUE THREAD

**Issue by xcambar** [Homebrew/legacy-homebrew#48631] opened 2016-01-30 11:01 UTC
Hi,
my $TERM is `xterm-256color-italic` (see https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/ for details) and though it works perfectly fine everywhere*, running `brew install whatever` generates a lot of the following messages:

> tput: unknown terminal "xterm-256color-italic"

Where it gets interesting is that I can run `tput` commands from the prompt without any error. It seems to be Homebrew-specific.

---

*: with the notable exception of ssh sesions, but that's a different story.

**Comment by bfontaine** [comment] 2016-01-30 13:25
Does `/usr/bin/tput cols` print any error in your terminal?

**Comment by xcambar** [comment] 2016-01-30 15:38
It does not.

```sh
$ /usr/bin/tput cols

158

$ echo $?

0
```

**Comment by apjanke** [comment] 2016-01-30 20:42
I wonder if there is some terminfo customization that is not getting passed along to `brew` and the programs it shells out to, possibly environment variables like `$TERMINFO_DIRS`, due to them not being exported, or removed by Homebrew's ENV setup or sandboxing support. Probably not an `export` issue, since the external command `/usr/bin/tput` seems to recognize it.

Where did you install your custom `xterm-256color-italic` definition to? If you just followed the instructions in that link and ran `tic` without additional options, I believe it will install to `~/.terminfo` instead of the system terminfo database.

I can reproduce similar warnings on my system by using a bogus TERM. This is on OS X 10.9.5.

```
janke@eilonwy:~ $ export TERM=bogus
zsh: can't find terminal definition for bogus
janke@eilonwy:~ $ brew install jasper
Cannot read termcap database;
using dumb terminal settings.
tput: unknown terminal "bogus"
==>
Already downloaded: /Library/Caches/Homebrew/jasper-1.900.1.mavericks.bottle.1.tar.gz
tput: unknown terminal "bogus"
==>
🍺  /usr/local/Cellar/jasper/1.900.1: 35 files, 898.0K
janke@eilonwy:~ $
```

But I set up that custom `xterm-256color-italic` entry according to the instructions in the link, and it didn't cause the warnings for me.

```
janke@eilonwy:~ $ tic xterm-256color-italic.terminfo
janke@eilonwy:~ $ export TERM=xterm-256color-italic
janke@eilonwy:~ $ brew install jasper
==> Downloading https://homebrew.bintray.com/bottles/jasper-1.900.1.mavericks.bo
Already downloaded: /Library/Caches/Homebrew/jasper-1.900.1.mavericks.bottle.1.tar.gz
==> Pouring jasper-1.900.1.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/jasper/1.900.1: 35 files, 898.0K
janke@eilonwy:~ $
```

In my scenario, `$TERMINFO` and `$TERMINFO_DIRS` are both unset.

```
janke@eilonwy:~ $ set | sort | grep -a TERM | grep -v '_comps\|signals'
ITERM_PROFILE='Solarized - Dark - apj'
ITERM_SESSION_ID=w0t1p0
TERM=xterm-256color-italic
TERM_PROGRAM=iTerm.app
janke@eilonwy:~ $
```

Could you post the outputs of `set | sort` and `env | sort` [as a gist](https://gist.github.com/) to help diagnose this?

**Comment by xcambar** [comment] 2016-02-01 09:43
Here's the gist: https://gist.github.com/xcambar/8ca42f1525c51611f043

**Comment by apjanke** [comment] 2016-02-02 06:13
I'm afraid I'm a little bewildered here. I don't see anything in your environment or shell variables that would be causing it. No TERMINFO customization there. And I still can't reproduce the behavior using the `xterm-256color-italic` definition.

**Comment by xcambar** [comment] 2016-02-02 10:19
The fact you have no problem is already enlightening.

I'll dig into my install and try to figure out something. More on that later

**Comment by jwhitley** [comment] 2016-02-17 01:14
I'm seeing the exact same issue, in my case with `TERM=tmux-256color` [due to this terrifically annoying workaround for new tmux 2.1 default behavior](https://github.com/tmux/tmux/blob/master/FAQ#L360).  In my case, `brew` is being run under tmux with the above setting for TERM.  Nothing I've run has any issue with this setup whatsoever.  AFAICT, there's some behavior particular to `brew` that's triggering this problem.

**Comment by apjanke** [comment] 2016-02-17 09:58
Interesting. This does seem `brew`-specific, but I can't figure out what's making it different.

Could we get the `brew config` output for your system? Maybe it'll shed a bit of light on things. Here's mine from 10.9.5, where user-defined terminfo entries are working okay.

```
$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 33bae41f9befda0d8c06ede428bcb69b31dfa21c
Last commit: 4 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.9.5-x86_64
Xcode: 6.2 => /Applications/Xcode-6.2.app/Contents/Developer
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/janke/.rvm/rubies/ruby-2.0.0-p643/bin/ruby
Java: 1.8.0_45, 1.6.0_65-b14-462
```

@xcambar, could we see `brew config` output for you too? 

@jwhitley: What did you use to create your `tmux-256color` terminfo entry? I'm on 10.9.5 and trying to use [the definition from that FAQ](https://github.com/tmux/tmux/blob/master/FAQ#L367-L372), but `tic` is failing on it for me.

```
[~]
$ cat tmux.terminfo
tmux|tmux terminal multiplexer,
	ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
	use=xterm+tmux, use=screen,

tmux-256color|tmux with 256 colors,
	use=xterm+256setaf, use=tmux,
[~]
$ tic -x tmux.terminfo
[1]    10657 segmentation fault  tic -x tmux.terminfo
[✘ ~]
$
```

**Comment by xcambar** [comment] 2016-02-17 12:17
Sure:

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: b9884695be87e9d642dc8b2fcf716c56f2235a3f
Last commit: 3 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11.1-x86_64
Xcode: 7.2
CLT: 7.2.0.0.1.1447826929
GCC-4.2: build 5666
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.0.0-p481/bin/ruby
Java: 1.8.0_20
```

**Comment by ilovezfs** [comment] 2016-02-17 17:11
@apjanke Does an ncurses issue look plausible: http://stackoverflow.com/questions/32798940/tput-unknown-terminal-xterm-256color

**Comment by jwhitley** [comment] 2016-02-17 18:47
Here's my `brew config` output:

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 30c54bc5cdbf0816c50706356a893f76463be2f5
Last commit: 23 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.3-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
GCC-4.2: build 5666
Clang: 7.0 build 700
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/whitley/.rbenv/shims/ruby => /Users/whitley/.rbenv/versions/2.2.3/bin/ruby
Java: 1.6.0_65-b14-468
```

**Comment by jwhitley** [comment] 2016-02-17 18:55
@apjanke Ah, that segfault appears to be tmux/tmux#194.  I clearly used a different variant I found shortly after the tmux 2.1 release.  Here's what I've got.  Put the following in `tmux-256color.ti` and try `tic` again:

```
tmux-256color|tmux with 256 colors,
	ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
	use=screen-256color,
```

**Comment by jwhitley** [comment] 2016-07-05 21:54
FWIW, I'm still seeing this issue in current Homebrew, just updated before this post.  Any further info I can provide?

**Comment by apjanke** [comment] 2016-07-14 17:38
@jwhitley I tried running a few `brew install`s under `tmux` using your updated terminfo entry, and wasn't able to reproduce those error messages. No new leads, sorry.

**Comment by jwhitley** [comment] 2016-07-14 18:06
Ah-ha!  At least as of Homebrew/brew@f6dad377b63946d403df7ed755fb14426a33df31, I'm not seeing the `tput:` problem with a typical "bottle-fed" `brew update && brew upgrade` run.  However, a source install is still triggering the problem.  Specifically `brew reinstall neovim`, where neovim was installed via `brew install --HEAD neovim` triggers this problem.

So it's possible that whatever was triggering this was (inadvertently?) fixed on some code paths, but not others.

```
>> brew reinstall neovim
==> Reinstalling neovim/neovim/neovim
==> Cloning https://github.com/neovim/neovim.git
Updating /Users/whitley/Library/Caches/Homebrew/neovim--git
==> Checking out branch master
tput: unknown terminal "tmux-256color"
==> Downloading https://github.com/libuv/libuv/archive/v1.8.0.tar.gz
Already downloaded: /Users/whitley/Library/Caches/Homebrew/neovim--libuv-1.8.0.tar.gz
tput: unknown terminal "tmux-256color"
==> Downloading https://github.com/luvit/luv/archive/146f1ce4c08c3b67f604c9ee1e124b1cf5c15cf3.tar.gz
Already downloaded: /Users/whitley/Library/Caches/Homebrew/neovim--luv-3.tar.gz
tput: unknown terminal "tmux-256color"
==> Downloading https://github.com/msgpack/msgpack-c/archive/cpp-1.0.0.tar.gz
Already downloaded: /Users/whitley/Library/Caches/Homebrew/neovim--msgpack-1.0.0.tar.gz
tput: unknown terminal "tmux-256color"
==> Downloading https://raw.githubusercontent.com/neovim/deps/master/opt/LuaJIT-2.0.4.tar.gz
Already downloaded: /Users/whitley/Library/Caches/Homebrew/neovim--luajit-2.0.4.tar.gz
tput: unknown terminal "tmux-256color"
==> Downloading https://github.com/keplerproject/luarocks/archive/5d8a16526573b36d5b22aa74866120c998466697.tar.gz
Already downloaded: /Users/whitley/Library/Caches/Homebrew/neovim--luarocks-998466697.tar.gz
tput: unknown terminal "tmux-256color"
==> Downloading https://github.com/mauke/unibilium/archive/v1.2.0.tar.gz
Already downloaded: /Users/whitley/Library/Caches/Homebrew/neovim--unibilium-1.2.0.tar.gz
tput: unknown terminal "tmux-256color"
==> Downloading http://www.leonerd.org.uk/code/libtermkey/libtermkey-0.18.tar.gz
Already downloaded: /Users/whitley/Library/Caches/Homebrew/neovim--libtermkey-0.18.tar.gz
tput: unknown terminal "tmux-256color"
==> Downloading https://github.com/neovim/libvterm/archive/1b745d29d45623aa8d22a7b9288c7b0e331c7088.tar.gz
Already downloaded: /Users/whitley/Library/Caches/Homebrew/neovim--libvterm-7088.tar.gz
tput: unknown terminal "tmux-256color"
==> Downloading https://github.com/jemalloc/jemalloc/releases/download/4.0.2/jemalloc-4.0.2.tar.bz2
Already downloaded: /Users/whitley/Library/Caches/Homebrew/neovim--jemalloc-4.0.2.tar.bz2
tput: unknown terminal "tmux-256color"
==> Building third-party dependencies.
tput: unknown terminal "tmux-256color"
==> cmake ../third-party -DUSE_BUNDLED_BUSTED=OFF -DUSE_BUNDLED_LUV=OFF -DUSE_EXISTING_SRC_DIR=ON -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/neovim/HEAD -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
tput: unknown terminal "tmux-256color"
==> make VERBOSE=1
tput: unknown terminal "tmux-256color"
==> Building Neovim.
tput: unknown terminal "tmux-256color"
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/neovim/HEAD -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DDEPS_PREFIX=../deps-build/usr -DCMAKE_BUILD_TYPE=Dev -DIconv_INCLUDE_DIRS:PATH=/usr/include -DIconv_LIBRARIES:PATH=/usr/lib/libiconv.dylib
tput: unknown terminal "tmux-256color"
==> make VERBOSE=1 install
==> Caveats
The Neovim executable is called 'nvim'. To use your existing Vim
configuration:
    ln -s ~/.vim ~/.config/nvim
    ln -s ~/.vimrc ~/.config/nvim/init.vim
See ':help nvim' for more information on Neovim.

When upgrading Neovim, check the following page for breaking changes:
    https://github.com/neovim/neovim/wiki/Following-HEAD

If you want support for Python plugins such as YouCompleteMe, you need
to install a Python module in addition to Neovim itself.

See ':help provider-python' or this page for more information:
    http://neovim.io/doc/user/provider.html

If you have any questions, have a look at:
    https://github.com/neovim/neovim/wiki/FAQ.
==> Summary
🍺  /usr/local/Cellar/neovim/HEAD: 1,333 files, 18M, built in 2 minutes 31 seconds
```

**Comment by jwhitley** [comment] 2016-07-14 18:10
@apjanke If you still can't repro w/ a source install, I'll try to repro with a clean install of Homebrew.  Failing that, I'll try again with a minimal, clean user account to help isolate any local environmental issues.

**Comment by MikeMcQuaid** [comment] 2016-08-10 09:20
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.

**Closed by MikeMcQuaid** 2016-08-10 09:20 UTC
