### ISSUE TITLE
radare2 0.10.1 is missing lua file(s)

### ISSUE THREAD

**Issue by zeha** [Homebrew/legacy-homebrew#50633] opened 2016-04-02 12:47 UTC
Installed radare2 from bottle (on 10.11.4):

```
radare2: stable 0.10.1 (bottled), HEAD
Reverse engineering framework
http://radare.org
/usr/local/Cellar/radare2/0.10.1 (658 files, 42.1M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/radare2.rb
==> Dependencies
Build: xz ✔, pkg-config ✔, valabind ✘, swig ✔, gobject-introspection ✔
Required: gmp ✔, libewf ✔, libmagic ✔, lua51 ✔, openssl ✔, yara ✔
```

When starting r2, it complains about syntax errors and a missing file:

```
 % r2 -
syntax error: error in error handling
syntax error: error in error handling
status=6, cannot open /usr/local/Cellar/radare2/0.10.1/lib/radare2/0.10.1/radare.lua: No such file or directory
```

**Comment by zunware** [comment] 2016-05-02 17:45
Im having this problem as well

**Comment by mikemcquaid** [comment] 2016-05-03 13:57
CC @DomT4 for Lua skills.

**Comment by apjanke** [comment] 2016-05-04 20:10
It looks like radare2 0.10.2 (https://github.com/Homebrew/homebrew-core/pull/262) fixed the major part of this. It no longer complains about the missing `radare2.lua` file, which is now present in the lib directory.

It still gives me the two `syntax error: error in error handling` messages on startup, but starts up and appears to work: I can open files, dump code, and so on.

Did 0.10.2 take care of the "No such file" error for you? And is `r2` working normally aside from those error messages?

**Comment by zeha** [comment] 2016-05-04 20:59
Can confirm the described behaviour in 0.10.2.

**Comment by apjanke** [comment] 2016-05-05 00:00
Cool. How much are those "syntax error" messages bothering you? Can we close this out?

**Comment by zeha** [comment] 2016-05-05 10:24
I don't really know what I'm missing because of the error? Maybe we can make a new ticket in the new repo.

**Comment by apjanke** [comment] 2016-05-05 15:07
Nah, let's just leave this one open for a bit. I'll look in to it some more.

**Comment by mikemcquaid** [comment] 2016-05-06 10:19
If it works I think it's probably worth closing this out in favour of a PR later.

**Comment by apjanke** [comment] 2016-05-06 14:31
I filed an upstream bug asking for some info: https://github.com/radare/radare2/issues/4793

If there's no observable behavior problems, yeah, let's close this out until one crops up, or we hear from upstream that those errors are significant and/or how to fix them.

@zeha: If you run in to any issues or unexpected behavior that might be related to this, yes, please open a new ticket in the new repo. But aside from having more info like that, this might just be cosmetic, and I don't think there's anything we can do about it at this point.

**Closed by apjanke** 2016-05-06 14:31 UTC
Labels: lua

**Comment by apjanke** [comment] 2016-05-08 17:50
After discussing with upstream a bit, this "error in error handling" looks like a harmless cosmetic problem with the Lua scripting that's used for the `r2` REPL UI. Will continue looking in to it because it would be nice to clean up, but I don't think you have to worry about any functional problems here.

**Comment by zeha** [comment] 2016-05-08 19:54
Cool, thanks for checking with upstream on that :)
