### ISSUE TITLE
DBus gives unix_domain_listener error and crashes after trying to connect to session

### ISSUE THREAD

**Issue by atemple84** [Homebrew/legacy-homebrew#49580] opened 2016-02-26 23:09 UTC
# Please follow the general troubleshooting steps first:

- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:
This is on OSX El Capitan 10.11.3.

I can no longer use dbus from brew ever since I updated it (d-bus-1.10.6.el_capitan.bottle.tar.gz). After commenting out the ServiceIPC items from the plist file, it starts fine without errors. After tracing the /var/log/system.log file, I see this error whenever I run my program (Qt) that tries to establish an interface with the session dbus:

`Feb 26 15:53:45 MacBook-Pro com.apple.xpc.launchd[1] (org.freedesktop.dbus-session[5297]): Could not activate socket group: unix_domain_listener: 37: Operation already in progress Feb 26 15:53:45 MacBook-Pro com.apple.xpc.launchd[1] (org.freedesktop.dbus-session[5297]): Service exited with abnormal code: 1`

So when I do a launchctl list on the dbus process, it changes from 0 to 1. This was working fine before I updated brew (so before el capitan?).

**Comment by dunn** [comment] 2016-02-28 17:13
I think @DomT4 knows the most about the currently problems with dbus.

**Comment by atemple84** [comment] 2016-03-04 15:33
This has gotten no attention for a whole week, and I really need dbus working... In the meantime, is there a way to install an older version of dbus? Possibly macports?

**Comment by dunn** [comment] 2016-03-04 16:08
You could try MacPorts or Fink, or `brew edit dbus` and change the `url` and `sha256` to an older version.

**Comment by DomT4** [comment] 2016-03-04 16:29
Sorry, I do so much stuff around Homebrew PRs/Issues I didn't even see Alex's original ping in my inbox. 

I wouldn't be surprised if this was El Cap specific given the depth of things SIP now blocks or silently kills, but equally `d-bus` has never worked completely perfectly on OS X because upstream hasn't been that interested in making it do so.

MacPorts are applying some patches we don't, but I have no idea if they've ever been submitted or reviewed upstream. Several maintainers have tried to work on this over time but once you go down the rabbit hole it's hard to get out. If you're passionate about this, helping poke around various solutions applied elsewhere and checking for upstream bugs is the sort of thing that helps make progress.

**Comment by atemple84** [comment] 2016-03-04 16:35
Thank you, Dunn!! I had a different issue with MacPorts dbus version, something about "inherently inefficient."

So I tried your suggestion of using brew edit dbus to install an older version. Using the links I saw version 1.8.20, so I changed the file to this:

`  #url "https://dbus.freedesktop.org/releases/dbus/dbus-1.10.6.tar.gz"
  #mirror "https://mirrors.ocf.berkeley.edu/debian/pool/main/d/dbus/dbus_1.10.6.orig.tar.gz"
  #sha256 "b5fefa08a77edd76cd64d872db949eebc02cf6f3f8be82e4bbc641742af5d35f"
  url "https://dbus.freedesktop.org/releases/dbus/dbus-1.8.20.tar.gz"
  mirror "https://mirrors.ocf.berkeley.edu/debian/pool/main/d/dbus/dbus_1.8.20.orig.tar.gz"
  sha256 "5c4fbf4c64621c96e871da91d2b729a5b00536e116d3c4612a469d924b1b703a"
`
On install, I got this in console:

`==> Downloading https://homebrew.bintray.com/bottles/d-bus-1.8.20.el_capitan.bot

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "d-bus"
Download failed: https://homebrew.bintray.com/bottles/d-bus-1.8.20.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://dbus.freedesktop.org/releases/dbus/dbus-1.8.20.tar.gz
Already downloaded: /Library/Caches/Homebrew/d-bus-1.8.20.tar.gz
==> ./configure --prefix=/usr/local/Cellar/d-bus/1.8.20 --localstatedir=/usr/loc
==> make
==> make install
==> /usr/local/Cellar/d-bus/1.8.20/bin/dbus-uuidgen --ensure=/usr/local/var/lib/
==> Caveats
To load d-bus:
  launchctl load ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist
==> Summary
🍺  /usr/local/Cellar/d-bus/1.8.20: 39 files, 1.8M, built in 32 seconds
`

After loading the LaunchAgent, I can now run my DBus applications!!! I'm very excited to find a workaround. Doesn't fix why the current DBus version doesn't work, but at least my old one does.

Thanks again!

**Comment by mikemcquaid** [comment] 2016-03-04 16:51
> This has gotten no attention for a whole week, and I really need dbus working... In the meantime, is there a way to install an older version of dbus? Possibly macports?

@atemple84 Please be patient. We run a project for free in our free time.

**Comment by UniqMartin** [comment] 2016-04-07 17:51
Closing as the issue has been resolved, though in a somewhat hackish way. @atemple84, if you care about this not suddenly falling apart in the future, this is your chance to make a valuable contribution by figuring out what needs to be done to fix this for an up-to-date `d-bus` and submit that as a PR. Thanks!

**Closed by UniqMartin** 2016-04-07 17:51 UTC

**Comment by atemple84** [comment] 2016-04-07 18:01
Well I wouldn't consider reverting to a version that didn't introduce the bug a fix... I'm not Homebrew developers like you guys, so all I can really do is suggest theories. I'm more surprised that there aren't other users of DBus, because this is a complete blocker until the workaround. (this was VERY work critical to me until you all showed me how to revert to an older version).

It's possible that when I reverted, DBus got recompiled from older source on my local machine and worked, which "may" imply that the current pre-compiled version of DBus in Homebrew isn't compatible with the latest MAC version. Just a theory, though. Again, I'm no Homebrew developer, I just needed a DBus server to be able to do my job (which apparently there's very few people using DBus on MAC).

**Comment by UniqMartin** [comment] 2016-04-07 18:13
Homebrew is a project that we run in our spare time and we depend on input from the community, more so for formulae like `d-bus` none of us maintainers uses. If it was really that critical to my work, I would try to work towards a real solution for the current or a future version, as simply reverting back normally isn't an option for Homebrew.

Have you tried investigating with the D-Bus project whether this is a known regression and if it's not known yet, reporting it upstream so that things can improve in a future version?

> It's possible that when I reverted, DBus got recompiled from older source on my local machine and worked, which "may" imply that the current pre-compiled binaries of DBus in Homebrew isn't compatible with the latest MAC version.

It's not very likely, but possible. To rule that out you could build the up-to-date version from source instead of using our bottled (pre-compiled) binaries. You can do that with `brew install d-bus --build-from-source`. If that solves the issue, that would be good to know.

**Comment by atemple84** [comment] 2016-04-07 18:21
Thank you, Martin. I will try the manual build-from-source and report back. I didn't realize there was a more specific D-Bus project to report issues, so if I still do have issues with the latest, I'll track down where I can report issues directly through the D-Bus project. Thanks again for the response.

This may be a good exercise anyways since MAC has updated their latest OS version and developer tools since the reporting of this bug...
