### ISSUE TITLE
MPI requirement `:recommended` doesn't allow building software with MPICH

### ISSUE THREAD

**Issue by goxberry** [Homebrew/legacy-homebrew#48900] opened 2016-02-06 01:11 UTC
If MPI is `:recommended` in a formula, then Homebrew tries to build `open-mpi` even if `mpich` is installed; the formula should build regardless of whether `mpich` or `open-mpi` is used. Ostensibly, there isn't anything wrong with the formula itself, so I don't think it's a homebrew-science issue, but rather some sort of issue in core with how [MPIRequirement](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/requirements/mpi_requirement.rb) handles recommended MPI dependencies.

Example: [hypre](https://github.com/Homebrew/homebrew-science/blob/master/hypre.rb).

```
bash-3.2$ brew install hypre
==> Installing hypre from homebrew/science
==> Installing dependencies for homebrew/science/hypre: open-mpi
==> Installing homebrew/science/hypre dependency: open-mpi
Error: Cannot install open-mpi because conflicting formulae are installed.

  mpich: because both install mpi__ compiler wrappers

Please `brew unlink mpich` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```

**Comment by UniqMartin** [comment] 2016-02-06 10:54
Thanks for the report, but this is expected behavior. Let me explain: MPI implementations differ vastly and even if they provide a mostly compatible API, their ABI is usually incompatible (this is certainly true for `mpich` and `open-mpi`). When you try to install `hypre`, by default you get the precompiled binaries (bottle), that are built against the default MPI provider, which happens to be `open-mpi` for Homebrew. Thus if you install the bottled `hypre` you get a hard dependency on `open-mpi`, even if you have another MPI implementation installed. (I acknowledge the error message isn't optimal, but I don't think we can easily improve this at the moment.)

You can install `hypre` from source to get it to work with `mpich`: `brew install hypre --build-from-source`.

**Comment by goxberry** [comment] 2016-02-07 00:31
> Thanks for the report, but this is expected behavior.

This should be written somewhere in the Homebrew docs. Having filed numerous issues to homebrew-science (plus one or two to core) to the effect of, "theoretically, you should be able to build any package with an MPI dependency with either MPICH or Open MPI, but Homebrew insists on using Open MPI the majority of the time", this is the first I've heard of it.

> Let me explain: MPI implementations differ vastly and even if they provide a mostly compatible API, their ABI is usually incompatible (this is certainly true for mpich and open-mpi).

Yes, I agree. I develop with MPI frequently, so I am aware of this issue; I am not looking to install both concurrently. Since you're the first homebrew maintainer/dev I've interacted with that seems somewhat knowledgeable about MPI, do you have any idea why Homebrew defaults to Open MPI? MPICH is a reference implementation and generally supports more of the MPI standard earlier.

> When you try to install hypre, by default you get the precompiled binaries (bottle), that are built against the default MPI provider, which happens to be open-mpi for Homebrew. Thus if you install the bottled hypre you get a hard dependency on open-mpi, even if you have another MPI implementation installed.

I understand (and expect) that bottles will be brewed with open-mpi, so I thought homebrew would just build hypre from source, and was confused when it didn't and returned an error instead.

> (I acknowledge the error message isn't optimal, but I don't think we can easily improve this at the moment.)

I think as long as there's somewhere that people can look for this information in the docs, that would help people resolve these sorts of corner cases without filing GitHub issues. (Ideally, they'd look in the GitHub issues, also.) I will update my brew bundle accordingly.

**Comment by UniqMartin** [comment] 2016-02-07 01:59
> This should be written somewhere in the Homebrew docs.

I agree. I'm not sure what the best place for this piece of information would be, though. Maybe the [FAQ](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md), maybe someplace else? Could you try to find a suitable location, write a paragraph or two explaining the situation, and then submit that as a pull request? That would be greatly appreciated! Feel free to mention me in the PR or to link me to it so I don't miss it.

> […], do you have any idea why Homebrew defaults to Open MPI? MPICH is a reference implementation and generally supports more of the MPI standard earlier.

As far as I can tell this is for historic reasons and because there hasn't been a sufficiently convincing argument yet to change the default. You can read more about it in #46712.

> I understand (and expect) that bottles will be brewed with open-mpi, so I thought homebrew would just build hypre from source, and was confused when it didn't and returned an error instead.

You're not the first to be confused and might enjoy reading #46553. :wink: The trouble really is that once Homebrew has decided that a formula should be installed from a bottle, it builds the dependency tree (according to the rules that apply for bottles) and then attempts to realize it. As far as I know it doesn't take into account conflicting formulae until it actually tries to install one of them, at which point it cannot backtrack anymore. Even if it could, there's no strategy that would allow it to automatically switch to a from-source build. (Take this information with a grain of salt, as I'm the youngest member of the team of Homebrew maintainers.)

**Comment by UniqMartin** [comment] 2016-04-07 17:59
@goxberry If you care about this being documented, please open a documentation PR (and feel free to mention me, so I don't miss it). Closing as there's nothing actionable here.

**Closed by UniqMartin** 2016-04-07 17:59 UTC
Labels: usability
